### ISSUE TITLE
Join Email List 

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#100]
Facebook has a new feature on its business pages that allow people to join a company's email list straight from Facebook. We of course want them to come here to the Epic site to sign up for the email list. Of course, going to epicraces.com takes them to the top of the page instead of to the email-list sign-up. Is there any kind of link or direct URL that would take someone not to the top of the page, but directly to that Subscribe field?

**Comment by brashrebel** [comment]
Not currently on the site. Theoretically we could make a "subscribe" page that has nothing but the subscribe form. Most likely though iContact will give you a special link that you can use. I haven't used it much but I know with other email apps like that, wherever you get the embed code you can also get a link to a subscribe page hosted by them. Usually also includes features for editing it and putting in things like links to your site. I'd recommend exploring that.

**Comment by AnaHotaling** [comment]
I got it! Thanks!
