### ISSUE TITLE
Font Size and Font

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#106]
Please change the default font size to 15.  
ALSO - just happened to notice our default fonts have changed???? We used to have Capture It and another that I can't remember.  EVENTS and the Title both were Capture It and the headers were the one I can't remember. Please look into this!

**Comment by evasolo** [comment]
P.S.  The other font is Allerta Stencil

**Comment by evasolo** [comment]
Just checking on this again.  I see the fonts reverted back to Capture It and Allerta Stencil, but our default font for event pages is still very small.   We would like it set to 15 pt.  Thank you.

**Comment by d4mation** [comment]
I have adjusted the Font Size for everything within the main page content to `16px`. Adjusting the text within the header causes some issues as the sizes of the menus and the social icons, for example, are calculated based on the Font-Size.

But if the Font-Size needs to be adjusted there too, let me know and I'll figure out a way to adjust the calculations to allow for it. My primary concern with doing that is that it would force the header image to be larger to accommodate a larger Events Menu.

**Comment by d4mation** [comment]
Actually, it turned out to be pretty quick to adjust the font sizes in the header. It didn't bother the header image at all! :+1: This is on your live site!

**Comment by evasolo** [comment]
HI Eric,
The default text on our event pages doesn't look any larger.  Just
confirming that it is actually 16 pt. font?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: www.epicraces.com e: eva@epicraces.com

**Comment by d4mation** [comment]
Yep, the base font-size is now 16px. 

![image](https://cloud.githubusercontent.com/assets/7770631/23551665/cd300692-ffe5-11e6-9251-694b16f09aa4.png)

Here's the same text with the old configuration:

![image](https://cloud.githubusercontent.com/assets/7770631/23551684/ede25e62-ffe5-11e6-9fe5-99290ca55637.png)
