### ISSUE TITLE
Global sponsor carousel

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#11]
Inspired by sites like [this](http://www.grandrapidstri.com/sponsorship/our-sponsors/) (at the bottom of the page), the client would like to add a carousel to the footer site wide which will scroll through grayscale versions of the main sponsor logos. We'll then need to convert the current custom field for putting a sponsor on the home page to simply be global sponsor and then use that to query the right sponsors. This is because only some sponsors actually sponsor _all_ events whereas others sponsor _specific_ events.

**Comment by d4mation** [comment]
There's a [CSS Filter](http://caniuse.com/#feat=css-filters) we could use to make the image grayscale, but it isn't supported in IE and some older stuff.

Should I look around for a way to polyfill that, or should we just add a secondary image field for a grayscale image?

Edit: Actually, it looks like the example is using the exact CSS I had in mind. Even with an SVG fallback for older browsers. Neato.

**Comment by d4mation** [comment]
I was going to throw this up on Staging as an example, but it looks like the Live->Staging functionality in WP Engine isn't working at the moment. 

After the big security breach last night they are probably fairly busy over there doing damage control... :/

Anyway, here's a screenshot. They regain their color when you hover over them.

![image](https://cloud.githubusercontent.com/assets/7770631/11723841/5f6f29d4-9f3e-11e5-87f4-89a8f977cb70.png)

**Comment by d4mation** [comment]
[It is now on Staging](http://epicraces.staging.wpengine.com/) along with #9.

**Comment by brashrebel** [comment]
@d4mation- can you deploy this to production please?

**Comment by d4mation** [comment]
Deployed!
