### ISSUE TITLE
Facebook pixel code feature

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#113]
We need to give Epic a way to add their Facebook pixel tracking code. Probably a setting in the admin where they can enter the code themselves.

**Comment by brashrebel** [comment]
@BigActual this needs to go on the to-do list. Do you have any time frame that I can tell Eva? It is a fairly simple enhancement.

**Comment by BigActual** [comment]
https://www.facebook.com/business/help/651294705016616

**Comment by d4mation** [comment]
Activated PixelYourSite on EpicRaces just now and set it up so that their User Role should be able to fully configure it.

**Comment by BigActual** [comment]
Eva indicated that she would set this up if it wasn't hard. I sent her directions by email.

**Comment by d4mation** [comment]
The plugin has links to documentation and YouTube videos throughout, so I
think she can figure it out :+1:
