### ISSUE TITLE
Social Media Icons on mobile version

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#114]
Is there any way to get the social-media icons that show up on our homepage in desktop (top left of the page) to also show up in the mobile version? Or, if not, have a link at the bottom that lets someone switch to desktop version from mobile version? Or does the site's theme prevent this?

**Comment by joelworsham** [comment]
I went ahead and moved them into the menu on mobile. They needed to be big enough to tap with a finger, but not make the "sticky header" any taller.

![](http://d.pr/i/VPtnG+)
