### ISSUE TITLE
Odd gray appearing under hero image

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_EPIC#115]
![image](https://cloud.githubusercontent.com/assets/8271108/25273837/8e6b7684-265b-11e7-88d5-bfeb7bd476de.png)
![image](https://cloud.githubusercontent.com/assets/8271108/25273856/9e88b48c-265b-11e7-9992-6a3a2586615e.png)
This could be a local issue. If you can't replicate it, then likely it's my chrome browser.

**Comment by d4mation** [comment]
Doesn't happen on my end. 

Mac OS X 10.12.4 (Sierra) with Chrome v57.0.2987.133 (64-bit)

**Comment by d4mation** [comment]
Desktop is a few updates behind most likely since it has been unplugged for a few weeks, but same results on Windows 10 Pro v1607 with Chrome v56.0.2924.87

![image](https://cloud.githubusercontent.com/assets/7770631/25283308/5089ad60-2681-11e7-83b1-14b13efdc0a6.png)

**Comment by d4mation** [comment]
And it would only likely be a "few updates behind" since I know that last week there was a larger Windows 10 update that came out. I'd imagine it wouldn't make much difference here though.
