### ISSUE TITLE
Disable comments for Work for Epic! page

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#119]
Went to disable the comments and pingbacks for the Work for Epic! page, and I don't have the option to do this. Can you please disable this for us?

**Comment by d4mation** [comment]
Is "Discussion" enabled under "Screen Options"?

If it is, the ability to Toggle Comments should show up at the bottom of your screen.

![image](https://cloud.githubusercontent.com/assets/7770631/25878457/cd05ae0e-34f8-11e7-92f7-758fa14227ab.png)

**Comment by AnaHotaling** [comment]
Got it! Thanks!
