### ISSUE TITLE
Forward event URL to another event URL

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#12]
We've done away with the Ann Arbor Tri: GrizzlyMan. The Ann Arbor Tri: WolverineMan is now being called the Ann Arbor Triathlon (aka the WolverineMan). Eva had me delete the GrizzlyMan event page on both our site and on the registration site. 

Apparently people have been emailing her, asking about GrizzlyMan. I'm guessing it's from past event calendars and write-ups found online. She would like people who go to:

http://epicraces.com/event/grizzlyman

to be automatically forwarded to:

http://epicraces.com/event/wolverine-man-triathlon/

I've already recommended that the grizzlyman.com domain be forwarded as well. Thanks!

**Comment by brashrebel** [comment]
All set!
