### ISSUE TITLE
Gray area on Featured Events

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#125]
From the document:

> The gray area is gray because your initial intention was for us to put a photo over it.  Now that the photo is at the top, it can be a more pleasing color.

**Comment by d4mation** [comment]
@evasolo Do you have a particular color in mind? One benefit to the gray is that it will always contrast with the Category colors.

**Comment by evasolo** [comment]
I think it could just be white, or a nicer gray?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
I just pushed a change for this to http://epicraces.staging.wpengine.com/.

Let me know what you think of it.

**Comment by d4mation** [comment]
@evasolo This need approval on Staging before it can be pushed Live.

**Comment by evasolo** [comment]
I'm sorry, what is the issue, I am looking at this in email and don't see a
thread.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
The gray color on the Featured Events on the Home Page. I changed the coloring of it.

**Comment by evasolo** [comment]
staging or live?


Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
Staging.

**Comment by evasolo** [comment]
Looks good- thanks.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
This is now Live
