### ISSUE TITLE
White area behind logos on Featured Events

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#126]
From the Document: 

> The logos on the tiles should be transparent.  When we load transparent images, they continue to have a white box.  Is the white box permanent?

**Comment by d4mation** [comment]
@evasolo The white can be removed, but the logos may need adjusting for readability reasons when not against a white backdrop

![image](https://user-images.githubusercontent.com/7770631/45320549-fc316580-b510-11e8-812b-54bf90b42138.png)

**Comment by d4mation** [comment]
@evasolo @marieepicraces 

What are your thoughts on this? If the Logos were altered to be readable without a white backdrop I can remove it. But unless they're altered I think it is best to keep it for better readability.

**Comment by marieepicraces** [comment]
I agree, we want them to be readable, so keep the backgrounds until they
are altered to not need them!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by evasolo** [comment]
We have somebody working on them, but yes, keep as-is for now.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com
