### ISSUE TITLE
Color Changes for Event Categories

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#127]
From the document: 

> For the dropdown menu of event categories we would like this order:
> Run - Orange
> Goddess - Pink
> Triathlon - Blue
> Duathlon - darker shade of blue toward transitioning to Indigo
> Aquabike - darker once again
> Swim - Indigo
> Bike- Green
> Kids - Purple

**Comment by d4mation** [comment]
@evasolo

I have implemented the color changes with the exception of Aquabike, Swim, and Kids. Do you have specific colors in mind for these? We pulled the rest from the palette above this section in the document.

**Comment by d4mation** [comment]
@evasolo @marieepicraces Have you had a chance to check this? We aren't sure what colors exactly the Aquabike, Swim, and Kids Categories should be made.

**Comment by evasolo** [comment]
Aquabike - darker once again - just do a shade darker than the one above in
the same family so it differentiates, but doesn't jump out
Swim - Indigo - this is one of the colors on the palette we sent you

Kids - Purple - this should have been on the palette, I will need to double
check, sorry, working on lots of different things right now.  LMK

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Lighter with a tinge of blue.

**Comment by BigActual** [comment]
I made the corrections we discussed yesterday. I also make a command decision and took skiing to yellow, which is the color for an intermediate level sign. There was too much blue going on. I'd happily take constructive criticism on the change. Another blue wasn't working at all though.
@evasolo @maryepicraces  @marieepicraces - What do you think?

**Comment by evasolo** [comment]
I'll check on the yellow- BUT - blue is intermediate!

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Oh, we were thinking different stuff. This is what I had in mind. You're absolutely right though.
![image](https://user-images.githubusercontent.com/8271108/45708679-0e825380-bb50-11e8-8452-99b1b18811a7.png)

**Comment by evasolo** [comment]
Aha! Got it.  I was thinking greens, blues, blacks.  Working on the color -
yellow may be fine, but I'm looking at some other pieces of our marketing.
Stay tuned.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
@evasolo Have you had a chance to look over the other pieces of your marketing for alternate colors?

**Comment by evasolo** [comment]
Virtual still needs to be taken off.  Please take ski off completely since we only have one ski race and don't plan to add more.

**Comment by d4mation** [comment]
Removed.

You can edit these here: https://epicraces.com/wp-admin/edit-tags.php?taxonomy=tribe_events_cat&post_type=tribe_events

The "Show in Category Select" option controls whether or not it shows in the Dropdown on the Home Page.

![image](https://user-images.githubusercontent.com/7770631/45905183-75587480-bdbd-11e8-8d29-02dfbdc15e94.png)
