### ISSUE TITLE
Home Page Hero not showing properly on some screens

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#128]
![image](https://user-images.githubusercontent.com/7770631/45320776-92658b80-b511-11e8-90c4-78af4595997b.png)

**Comment by d4mation** [comment]
@evasolo

I have this fixed on http://epicraces.staging.wpengine.com/. Can you check that for me?

**Comment by d4mation** [comment]
@evasolo @marieepicraces Have you had a chance to check the Staging site to see if this fix works for you?

**Comment by evasolo** [comment]
what is the staging site?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
http://epicraces.staging.wpengine.com/

I think that when you reply by email it doesn't show you the full context of the Issue, unfortunately. I had linked it higher up in the Issue so I didn't think to paste the link again. I'm sorry about that.

**Comment by BigActual** [comment]
Is this issue regarding the transparency overlay in #142 ?

**Comment by d4mation** [comment]
This is different. In the screenshot provided in the Google Doc, some of the text for the button is being cut off on the screen. I was only able to get close to reproducing when I adjusted the height of my window.

**Comment by BigActual** [comment]
Ah, thanks for the clarification, Eric. @evasolo, I believe we can close this issue. Do you agree?

**Comment by evasolo** [comment]
Yes, resolved.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com
