### ISSUE TITLE
Home Page Hero Color/Content/Image Changes

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#129]
From the document: 

> I understand you darkened the photo to be able to see the text, but that seems like a silly workaround.  Can you make the text a different color or tweak the layout- which needs to be changed anyway since the button is hidden? I don’t think we actually need that button, there are plenty of places to click without it.

**Comment by d4mation** [comment]
@evasolo

Here's our notes:

From @BigActual : 

> This is the maiin call to action on the site. Let’s not eliminate the button. Let’s point it at the next race. That’s the number one reason people come to the site. This image and call to action should be changed to go to the next race, with each race.

From me: 

> This is tricky, since changing the text color is also just a workaround. Generally, it is best to make the image fit contrast-wise rather than altering the text color since since if the image is swapped out in the future, the text would likely need altered again. Having a standard for acceptable images may be best.
>
> Also, it looks like the image is different now? It is much harder to read now. I am willing to look into ways to increase readability, but most of of them would include changing/altering the image. With most images, it can be very hard to achieve a uniform contrast without some kind of overlay. There are so many color changes throughout the photo (clothing, signs, skin color, etc.) that choosing a singular text color that stands out would be near impossible. This is why with movie subtitles, they often have a black overlay behind them to ensure you have good readability across multiple scenes.
>
> This is my screen right now: 
> ![image](https://user-images.githubusercontent.com/7770631/45320948-f7b97c80-b511-11e8-88bd-f16c5724211f.png)

**Comment by BigActual** [comment]
Just an FYI as we work through this. The overlay is a 55% black. It was the amount that makes the content above it "work."
@evasolo - Also, the image is being smushed in some odd fashion. It's overly grainy. Whoever is taking responsibility for creating the hero image should spend some time with me to learn how to do this more effectively. I'd be happy to teach some tricks.

**Comment by d4mation** [comment]
@evasolo 

I copied the documentation that Joel made into the Wiki here: https://github.com/realbig/RBM_TH_EPIC/wiki/Creating-an-Event#hero-image

While this bit is specific to Events, it holds true for the Hero on the Home Page as well.

**Comment by d4mation** [comment]
Going to close in favor of #142 since work seems to have transitioned there.
