### ISSUE TITLE
Testimonials Image Option on Home Page not working

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#130]
From the document: 

> I put a photo behind the Testimonials in the designated space in the backend and it doesn’t show up.

**Comment by d4mation** [comment]
@evasolo Let me know if this looks correct on Staging. http://epicraces.staging.wpengine.com/. I believe I have corrected the problem.

**Comment by d4mation** [comment]
@evasolo @marieepicraces Have you had a chance to check Staging for this fix?

Looking at the code, it seems the option on the Home Page was meant to be a "fallback" background image for the Testimonials. The Testimonials can also be given individual background images when editing the Testimonials themselves.

**Comment by evasolo** [comment]
I tried to do that and it didn't work.  Can you either send instructions or
can we set up a brief phone call so you can walk me through?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
Did you test it on Staging? This feature isn't properly implemented on the Live Site at this time.

http://epicraces.staging.wpengine.com/

I also just pushed a minor fix to ensure that setting the Featured Image on a Testimonial properly overrides the Default image that you can set when editing the Home Page.

**Comment by BigActual** [comment]
We tried this on staging last night, both Eva and I. Neither of us saw the "Featured Image" show on the home page view for Testimonials, nor did we see it on the Testimonials Archive page.

**Comment by d4mation** [comment]
Middle one is using a Featured Image. Other two are using the setting from Editing the Home Page (A default fallback). This screenshot is from my local, but I just confirmed that this also works on Staging: http://epicraces.staging.wpengine.com/wp-admin/post.php?post=8731&action=edit

![image](https://user-images.githubusercontent.com/7770631/45710206-fad8ec00-bb53-11e8-97c4-9c3d6002f8d2.png)

> nor did we see it on the Testimonials Archive page

Are there mocks for how the Archive Page should look? I didn't realize there was an Archive.

**Comment by BigActual** [comment]
@evasolo - Both Eric and I have confirmed this on staging. If you approve, we can move this change to live and close the issue?

**Comment by evasolo** [comment]
So... do I need to go to 2 different places to set photos behind the
testimonials?  Not sure I'm understanding.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
The Testimonials Background Setting when editing the Home Page is just a default background.

![image](https://user-images.githubusercontent.com/7770631/45710820-bbab9a80-bb55-11e8-95ac-8be8f0dc4d15.png)

You can set a specific image to specific Testimonials when editing a specific Testimonial.

**Comment by evasolo** [comment]
Understood!  Give me a few minutes to test it before closing, please.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
@evasolo Did you have a chance to look into this? If it is all good, I can merge these changes in and push it Live.

**Comment by evasolo** [comment]
Yes, I'm sorry, I thought I had asked you Tuesday to push it live.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
This is now Live
