### ISSUE TITLE
Change “Gallery” to “Photos”

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#132]
From Document: 

> Change “Gallery” to “Photos”

**Comment by d4mation** [comment]
@evasolo

This should be corrected on http://epicraces.staging.wpengine.com/. Could you give that a check for me? I also corrected a problem I noticed where the Photos tab was getting added in cases where no Photo album was defined.

**Comment by d4mation** [comment]
@evasolo @marieepicraces Have you had a chance to check this fix on Staging? For fixes like this which aren't directly affecting workflow problems, I am pushing them to Staging first rather than directly to Live.

**Comment by marieepicraces** [comment]
How do we check on Staging? I missed that bit.


Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
Sorry, I am not sure how much goes into the emails that you receive; I put it into a previous comment.

Here's the link for Staging: http://epicraces.staging.wpengine.com/

**Comment by evasolo** [comment]
I just asked in a different email what staging is - sorry - I am reading
backwards. So, it's the big photo on the homepage?  Had not had a chance to
play with that.  As important as it is, I'm OK working on that next week.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
Nope, this Issue from what I understood in the Google Doc was that the text "Gallery" in the Legacy/Old Layout should be changed to "Photos".

**Comment by evasolo** [comment]
That is correct!

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
Just pushed this change to the Live site 👍
