### ISSUE TITLE
Home Page Testimonials - Slider

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#138]
# From Document: 

> Rather than the next and previous tiles, please do it like this- we have discussed as a team, and all agree that it should slide on its own every 15 sec in addition to folks have the ability to slide it faster using the arrows.
> ![image](https://user-images.githubusercontent.com/7770631/45431193-2439d980-b675-11e8-9a27-bac0c060f701.png)

# From Email: 

@BigActual's reply:

> Eva,
> I will work through the punch list. I’ll make the changes you’re requesting. However, I’m going to make one last ditch effort to talk you out of using a carousel anywhere, except under a product for sale of in a gallery of photographs for display in an event. I do this because I want you to be successful online, not to be obstinate. 
>
> Here is a glancing slice of the millions of pages of writings dedicated to avoiding this. My personal summation of this research is, carousels look useful but fail most of the time. Please, at least look at the first link, and if I can talk you out of anything, don’t make it auto-forward. 
> 
> http://shouldiuseacarousel.com/
> https://envato.com/blog/design-debate-image-carousels-ux-assets-liabilities/
> https://conversionxl.com/blog/dont-use-automatic-image-sliders-or-carousels/
> https://www.velir.com/blog/2014/04/18/why-you-shouldn-t-use-carousel-feature-content
> https://yoast.com/opinion-on-sliders/
> https://www.mightybytes.com/blog/5-alternatives-using-carousel-website-homepage/

> The problems:
> * You load assets for way more than you display. They take forever to load, especially on a cell phone in the field (It’s not fair to test that when you’re on your wifi in the Epic office or if you have already loaded the page on your phone at the office then go out in the field.)
> 
> * Accessibility is still an issue. Aria labels and screen readers just don’t handle these well.
> 
> * This is a feature that will be placed in a location on your website that diminishes consumer interaction instead of enhancing it. This will not provide the additional wow factor, pizzazz, or support of your program that you are looking for. It’s a distraction that sucks in the eye, confuses the user, fails to convey information and ultimately wastes the time of your audience or stops their surfing all-together.
> 
> * Anything that moves on it’s own is a distraction, not a supporting mechanism.
> 
> Possible Solution:
We recommend a grid layout of any assorted variety, that change every time the page loads; three up, or one and two, or many other combinations, and create a hyperlink that goes to a page of testimonials. But nothing that moves on it’s own. 
> 
> I’m passionate about this because I know what end users want. Ease of use, quick load times, simple work flows. If I hired your team to manage a race and was asking you to do something wrong. You’d tell me I was making a mistake and expect that I'd listen to your expertise. I’m hoping for that here. Sliders that move on their own ruin workflows.

@evasolo's reply:

> I completely understand what you're saying and in most website cases I agree with you, but signing up for a race is a unique situation.  It is not a site that folks typically go back to over and over again before signing up for a race.  We have about 30 sec - one minute to engage them to want to learn more as opposed to a website where somebody is looking for store hours, or news.
> 
> I don't mind if there are arrows as opposed to automatic sliding, but I don't like the "next" and "previous" buttons below.
> 
> How about if we have a new photo each time the page loads in addition to the arrows on the photo as opposed to the buttons?

# My Notes/Suggestions to follow

**Comment by d4mation** [comment]
Based on the title of the section in the Punchlist Document, this seems to be for the Testimonials on the Home Page.

The Home Page Testimonials are technically already a Slider, so that much is already implemented as part of Joel's design. It just doesn't have it's Next/Previous buttons as overlaid arrows as would be preferred.

@evasolo @marieepicraces Am I understanding this correctly?

If so, I'll work on moving them to arrow buttons rather than what is there now. I'll also see what I can do about having it load a different set of 3 for each page load, but randomness can be tricky as it often isn't directly supported due to performance/caching reasons.

**Comment by BigActual** [comment]
Additional information from the email conversation between Eva and I:

----------------
I completely understand what you're saying and in most website cases I agree with you, but signing up for a race is a unique situation.  It is not a site that folks typically go back to over and over again before signing up for a race.  We have about 30 sec - one minute to engage them to want to learn more as opposed to a website where somebody is looking for store hours, or news.

I don't mind if there are arrows as opposed to automatic sliding, but I don't like the "next" and "previous" buttons below.

How about if we have a new photo each time the page loads in addition to the arrows on the photo as opposed to the buttons?
--------------------

**Comment by evasolo** [comment]
We would like arrows

**Comment by BigActual** [comment]
Yes, they should be coming, instead of the buttons underneath.

**Comment by evasolo** [comment]
OK!  I am good with the photo uploads.

**Comment by d4mation** [comment]
This is now on Staging.

**Comment by d4mation** [comment]
@evasolo This need approval on Staging before it can be pushed Live.

**Comment by evasolo** [comment]
I thought I had already approved the testimonials.  They are good to be
pushed live.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
This is now Live
