### ISSUE TITLE
Forwarding URL from Issue #12 Does Not Work

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#14]
Saw that my request to have http://epicraces.com/event/grizzlyman forward to our page for the Ann Arbor Tri (WolverineMan) was closed. I clicked on the http://epicraces.com/event/grizzlyman link and got this:

Error 404 - Page not found!

The page you trying to reach does not exist, or has been moved. Please use the menus or the search box to find what you are looking for.

Can you please make sure that http://epicraces.com/event/grizzlyman forwards to http://epicraces.com/event/wolverine-man-triathlon/ ? Thank you!

**Comment by brashrebel** [comment]
Sorry, I closed the last issue because I had modified the redirect for grizzlymantri.com and not the Grizzly Man event on epicraces.com. I've now done that as well though it should take a few minutes before it takes affect.

Also, you are welcome to reopen issues if you believe they are not actually completed correctly.

**Comment by AnaHotaling** [comment]
LOL! I'm just starting to get used to using Github. I have no idea how to reopen an issue at this point! :D 

Thanks for redirecting grizzlymantri.com -- I thought that was something I would have to do on Go Daddy, so thanks for taking that off my To Do list! 

the epicraces.com/event/grizzlyman is still coming up as a 404. I think it's been a few minutes. I'm being impatient, aren't I? Sorry... Eva is leaving for vacation tomorrow and I'm trying to get as much of my list of To-Do's for her (and for me, so I can actually wrap presents and bake cookies. And run, I suppose).

**Comment by AnaHotaling** [comment]
Hi Kyle... just checked this (mainly because Eva thanked me for taking care of it) and it's still not forwarding. Could you please make sure this gets fixed? Thanks!

**Comment by brashrebel** [comment]
Looks like I entered the redirect incorrectly. Thanks for pointing this out. I've just fixed it.
