### ISSUE TITLE
Featured Image (Logo) Showing at the top of Event Single

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#140]
From Document: 

> We can’t have the featured image go to the logo on the tile as well as top of the event page.  Logos don’t work at the top of the event pages, we need images.

**Comment by d4mation** [comment]
@evasolo @marieepicraces I have a possible fix for this pushed up to Staging: http://epicraces.staging.wpengine.com/

It now shows what is in the Hero Image field. I also noticed some oddities with the Page Section layout regarding this, so I addressed those too.

**Comment by BigActual** [comment]
I think this is correct. @marieepicraces & @evasolo - Do you agree?

**Comment by evasolo** [comment]
We set a featured image for the private version of Hot Cocoa and we aren't
able to see it when we view the page.  Please keep Mary in the loop on this
as she has been working on the pages quite a bit.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
@maryepicraces Did you check for this fix on Staging? http://epicraces.staging.wpengine.com/

This fix is _not_ on Live yet.

**Comment by evasolo** [comment]
I didn't realize it wasn't live.  yes, it works in staging, but where does
the hero image go?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Change the fields so that the hero is for the hero image. The logo has it's own logo field and the Feature is used on the home page featured event tile.

**Comment by d4mation** [comment]
The Hero Image has its own upload field:

![image](https://user-images.githubusercontent.com/7770631/45650166-6ad76b80-ba9b-11e8-806d-0e82c85233b2.png)

The Logo is read from the Featured Image.

There is no dedicated Logo field that I am aware of.

**Comment by BigActual** [comment]
@d4mation - Clarification, We currently see two fields on the Event dashboard view but there should be three fields; a) Hero Image, b) Logo, and c)Feature Tile. Please label these with the ideal size so our client understands where best to crop the images. 

Our programming will place the:

- logo where it needs to go on both the Event Single and Home Page Feature Event tile
- Hero Image at the top of the Event Single
- Feature Tile image in the proper section of the tile.

**Comment by d4mation** [comment]
This has been pushed to Staging. I added a new field specific to the Tiles and added recommended sizes to each. 

If no Tile image is added, it will use the Hero Image as the Tile instead.

**Comment by BigActual** [comment]
@evasolo - These changes need to be pushed to live to satisfy Marie's request. Do you approve the changes?

**Comment by evasolo** [comment]
Yes

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
This is now Live
