### ISSUE TITLE
Epic In the News

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#141]
There seem to be 2 spots with news stories.  We only want one and we'd like links to the stories as opposed to blog styles.  Kind of like on FB when you attach a link, it shows a preview.  I like the spot on the homepage, but the blog isn't working- it says the stories are written by Ana, but they are news stories that were copied and pasted.  I have 2 I need to add asap- we will be on the news tonight and we were just featured in a national newsletter.

**Comment by d4mation** [comment]
So, to confirm:

You like the way that the News Stories look on the Home Page, but you want them to link directly to the News Article (an external site) that you've copied instead of taking them to another page on the Epic site, correct?

**Comment by evasolo** [comment]
Correct.  They are true news stories, not blogs.  We want to have a list of
times we've been in the news and share those stories, but not copy/paste
the stories so they look legit. I'd like folks to click and have it open a
new tab.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
I just implemented this on the Live site for you. 

When Editing a Blog Post, scroll to the bottom of the page and you'll be able to choose "A Custom URL" and you can put the link to the News Article there: 

![image](https://user-images.githubusercontent.com/7770631/45511189-44979000-b76a-11e8-9002-bde03b6b2743.png)

You may still want to copy/paste at least the first paragraph or so of the News Story in order for it to show the little snippet like you see on the Home Page. Otherwise it will only show the title.

**Comment by evasolo** [comment]
I went to the home page, went to the backend, scrolled down, and I don't
see where to add it.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
It isn't when editing the Home Page, but when Editing the Blog Posts themselves. If you click "Posts" when on the Backend of your site, you'll see all the Blog Posts.

![image](https://user-images.githubusercontent.com/7770631/45511485-1c5c6100-b76b-11e8-924e-635f1fe0c72c.png)

**Comment by evasolo** [comment]
OK, got it!  Cleaning them up and finding the "real" links.  Would there be
a way to have a little thumbnail photo or somehow have the link show up the
way a link posted on FB looks?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Eric and I have been discussing the best way to approach this enhancement. We have some ideas for creating this after we've cleaned up the post-launch items. @evasolo I'd like to close this item and open a new issue for the enhancement if you are happy with the addition Eric has included?

**Comment by evasolo** [comment]
That's fine.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com
