### ISSUE TITLE
Charitable Giving Chart not showing

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#145]

**Comment by evasolo** [comment]
We had a chart showing our past giving and it has disappeared.

**Comment by d4mation** [comment]
Can you link me to the page that this was meant to show on? That will help me determine what may have gone wrong.

**Comment by evasolo** [comment]
https://epicraces.com/charitable-giving/

**Comment by d4mation** [comment]
Pushed a fix for this to the Live site 👍
