### ISSUE TITLE
Add fields for Upload T-Shirt and Medal

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_EPIC#146]
2 T-shirt fields - Two different T-shirt Fitted Women's T-Shirt the other is Unisex
1 Medal Field
One editable title field for the section.
Need to be able to add additional items like another special chachkie or another t-shirt for special people.

**Comment by d4mation** [comment]
Where does this need to be? What is it meant to do?

**Comment by evasolo** [comment]
It needs to be a field on the event page.  Each race has a shirt (typically
2 versions) and a medal.  We would like to be able to keep all event pages
uniform so we'd like to have a consistent space to upload.  Sometimes we
have an additional giveaway so we'd like the option to add another image
field if needed.

Here is an example of what we have been doing.  The image, which is the
most important part, gets lost and just seems to be in random space:




Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
@evasolo 

Can you please log into GitHub and upload the example? When you reply by Email all Attachments get stripped out.

**Comment by evasolo** [comment]
Yes, I'll do that right now.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
Copied from #148 

![image](https://user-images.githubusercontent.com/7770631/45656796-5ef8a300-bab5-11e8-850c-952f2e758308.png)

**Comment by d4mation** [comment]
Just pushed this to Staging. There is now a new "T-Shirts and Medals" Content Block to add to your Page Sections which works very similarly to the Multiple Column Content Block.

The Images are set to always be centered within their column and the text that shows below them can be formatted however you need using the WYSIWYG. If there needs to be additional control given, let me know what you need to do and I'll try to make it happen.

**Comment by d4mation** [comment]
@evasolo This need approval on Staging before it can be pushed Live.

**Comment by evasolo** [comment]
Marie is testing it

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by marieepicraces** [comment]
Looking at this on Staging - is this basically a content block with an image field? I'm not sure how it will look on the user end since my test in staging didn't seem to work. I was trying to add the block to the HCC event, just to see how it looked. Advice?

**Comment by marieepicraces** [comment]
Okay, just trying again on staging and see it better now. What we had wanted with this block is the ability to add multiple images in a grid or column format, I believe. I'm not seeing a way to do that with an individual block so I'm wondering what the advantage is to this. As opposed to just using a content block with images, I mean.

**Comment by d4mation** [comment]
With this new block, you can add multiple and they get formatted into columns.

Example:

![image](https://user-images.githubusercontent.com/7770631/45838819-b464c800-bce0-11e8-84a6-153e00731771.png)

![image](https://user-images.githubusercontent.com/7770631/45838883-d3fbf080-bce0-11e8-91d2-3eaa732c3628.png)

^ There is the blue button at the bottom to add a new column.

Is there additional functionality that is needed? It seemed to me you needed a uniform way to put images and text into columns. Is there something else it needs to do?

**Comment by marieepicraces** [comment]
The columns are great but when I need to add explanatory text below it, the simplest solution to me is to create a global content block for this. Unfortunately, though, the title of that block then shows at the top of my page. See 
https://epicraces.staging.wpengine.com/event/hot-cocoa-classic/?preview_id=3534&preview_nonce=f3140fb556&_thumbnail_id=7494&preview=true#page-section-8f7f4c1c

as an example

**Comment by d4mation** [comment]
I can add in another WYSIWYG editor to go below the columns. Give me a few to get that situated.

**Comment by d4mation** [comment]
Just pushed that change to Staging. Let me know if that works for you 👍

**Comment by marieepicraces** [comment]
I'll give it a shot - is it a change to the t-shirts and medals block or is
there a new block? Not immediately obvious to me - thanks!


Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
It is a change to the T-Shirts and Medals block. It appears directly below the T-Shirts and Medals that you have added to the block.

**Comment by marieepicraces** [comment]
Oh, never mind! Answered my own question!


Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by marieepicraces** [comment]
Yep, saw it - it's great, thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
This has been pushed to Live 👍
