### ISSUE TITLE
search window?

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#147]
Glad we got to go over all of those details, Steve.  One thing I forgot to mention, is that early on we had discussed two things: one was a search window and the other was a contact us at the bottom of the page that looks like somebody is always there to chat.  I'm OK not having the chat window, but I'd still like a search window where they can put in a race name, etc. and get a list of options. Thanks!

**Comment by BigActual** [comment]
Yes, I do recall this request. @d4mation, please add a search field in the head section.

Just an FYI for Eva and the Epic team, by default, a search in WordPress will only search a post’s title and the post content. More creative search (I.e. Categories, tags, and other niceties require implementing things like filters.

**Comment by evasolo** [comment]
Thank you.  So, are you suggesting we add the filters when we create the
pages and posts?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Not necessarily. Just pointing out the search structure as it stands to bring you up to speed. Likely, we'll not need it. If we run into issues later with search limitations, our course of action would be to pursue additional tools. We're fine for now.

**Comment by d4mation** [comment]
This is up on Staging for review. http://epicraces.staging.wpengine.com/

**Comment by evasolo** [comment]
It seems to only be going to "pages", not events?  Is it possible to only
have it search events because the pages I found when I did a test search of
swim to the moon
are dated?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
I searched for "What's Your Mountain" and the Event showed up.

http://epicraces.staging.wpengine.com/?s=what%27s+your+mountain

Do you meant the "Posted on August 15, 2018 at 11:55 AM. Written by ana" type-blurb? That can be removed with a "Search Results Template" for Events if needed.

**Comment by evasolo** [comment]
Did you try Swim to the Moon?


Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
It shows up in those results, it is just further down the page.

![image](https://user-images.githubusercontent.com/7770631/45706208-a6307380-bb49-11e8-9479-4c40485c5607.png)

What we could do is prioritize Events in the Search Results so that they show first. Would that work?

**Comment by evasolo** [comment]
So... should we just delete irrelevant pages?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
You could delete any irrelevant pages that are no longer needed (May be best to do that on Live rather than Staging), or I could adjust the Search Results so that Events are forced to the top like I suggested.

**Comment by evasolo** [comment]
Let's just focus the search on the events since our goal is to get them to
sign up for events.  thanks!

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
Just pushed a change to Staging which will have it search _only_ Events.

Note about searching: 

If you search "Swim to the Moon", it is the second result. This is because Battle of Waterloo uses the word "swim" a _lot_ in its content and it is coming sooner than Swim to the Moon is. Once the Battle of Waterloo is over, the order will change to put "Swim to the Moon" at the top.

**Comment by evasolo** [comment]
Perfect!  Thank you!

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by evasolo** [comment]
Will you please put a space between search and the magnifying glass?
![search](https://user-images.githubusercontent.com/16295786/45709360-d67c1000-bb51-11e8-930d-61a083ce87ce.jpg)

**Comment by d4mation** [comment]
Just added a second Space in there. If that's good, I'll push this aspect Live 👍

**Comment by evasolo** [comment]
Yep- thank you!!

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Sorry, Eric, I bumped the close button on accident. I'll let you close it with your push.

**Comment by d4mation** [comment]
Pushed to Live 👍
