### ISSUE TITLE
Increase Number of Charity Partners on Ann Arbor Marathon page template from one to four

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#15]
We have four official charity partners for the Ann Arbor Marathon: Ronald McDonald House, Team RWB, the kite network, and JDRF. But... we only have the option of adding one partner in the template (mainly because we usually only have one main partner). Can this be increased to allow for all of our charity partners to be displayed? There are talks of a fifth and final one, but that has not been confirmed yet. Thanks!

**Comment by brashrebel** [comment]
Sure Ana. That will take about 1.5 hours of development time. Can you get Eva's approval for that please and I'll add it to our queue?

**Comment by AnaHotaling** [comment]
Spoke with Eva; she is wondering why the field was limited to only one charity partner to begin with, since the other fields allow us to select more than one partner. Could you let us know, please?

**Comment by brashrebel** [comment]
Sure Ana. First off, we didn't _limit_ this feature to only one charity partner. This feature was described to us a certain way so we developed a solution that fit. Accounting for a variable number of charity partners is significantly more complicated and at the time there was no reason to _add_ that functionality so we didn't. It is definitely an enhancement that would take some time but we're happy to do it.

**Comment by AnaHotaling** [comment]
Hello again! Eva's reply is that she would like to wait to increase the number of charity partners until the actual sponsors' display has been straightened out and is more visually appealing. She asks me to remind you that we've been working on making the sponsor section acceptable for the past several years and that this is getting to be a priority, since unhappy sponsors = ex-sponsors. Have you had a chance to look at the links of the sponsor pages I sent you for other races?

**Comment by brashrebel** [comment]
@AnaHotaling can you and Eva take a look at some of the screenshots for options over in #7 please? We mocked up 3 options for sponsor layouts and I meant to share them with Eva last week. I need to know which option to go with and if it needs any adjustments. Those 3 are roughly based on my last conversation with Eva. And if you have input, please leave it on that issue.

**Comment by AnaHotaling** [comment]
Saw that you closed #21. Eva noted that you specifically asked us to open a new issue regarding the charity partners, outside of this one (#15). Do you wish me to open another new issue (no one has shown me how to re-open an issue and I couldn't find instructions here)? Or should we continue here on #15? What Eva wants is to do away completely with the charity partner option and go with what I had explained in #21.

**Comment by brashrebel** [comment]
@AnaHotaling sorry about the confusion. In my comment above I meant that input relating to the sponsors layout should be on #7. This issue is about the Charity Partner's feature specifically so we can discuss it here. Or there, really it doesn't matter that much because the solution is the same either way and we'll close them both when it is done.

Yes, we can add this to our to-do list. Previously you said that Eva said we could do this after the sponsor's issue was done. That is now finished so can we proceed with this? As I mentioned before, this is an enhancement so there will be a charge.

**Comment by AnaHotaling** [comment]
Yes, I'll let Eva know ... thanks!

**Comment by AnaHotaling** [comment]
Eva sent an email to you approving this... did you receive it?

**Comment by AnaHotaling** [comment]
Eva has asked me to "retract" her approval. She has another idea for the featured charities. So... I guess we can close this issue for now. I'll open a new one if her idea doesn't pan out. :)
