### ISSUE TITLE
The button on the home screen needs to be able to be set to go to events, not just pages

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#151]

**Comment by evasolo** [comment]
![screen shot 2018-09-18 at 1 25 59 pm](https://user-images.githubusercontent.com/16295786/45705087-a67b3f80-bb46-11e8-95b2-8d53bad8c89f.png)

**Comment by d4mation** [comment]
This change is now on Staging.

**Comment by evasolo** [comment]
Events are now there, thanks.

**Comment by d4mation** [comment]
This change is now on Live
