### ISSUE TITLE
Still need to get rid of "next epic event"

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#152]
![screen shot 2018-09-18 at 3 33 15 pm](https://user-images.githubusercontent.com/16295786/45711655-42fa0d80-bb58-11e8-94ee-3dddaa2e9963.png)

**Comment by d4mation** [comment]
This is only on Staging. This does not exist on Live.

**Comment by BigActual** [comment]
Thanks for clarifying.
