### ISSUE TITLE
Please add Clay McKenzie as a user: clay@epicraces.com

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#153]

**Comment by BigActual** [comment]
What will Clay be responsible for on the site? I want to make sure he has access to the right tools.

**Comment by evasolo** [comment]
Adding photos, simple edits.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
User created.
