### ISSUE TITLE
Tile/Hero/Featured images not set correctly

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#154]
I tried to make some updates and they are not pointing to the right places- I'm not even sure what points where exactly, but when I put a logo in the Ugly Dog Featured Image it went to the tile and was not formatted correctly.

**Comment by d4mation** [comment]
Was this on Staging? Can you link me to the problem?

**Comment by BigActual** [comment]
The featured image would be the Tile. @d4mation , it may be appropriate to rename the field so that it's not confusing if it makes the task simpler for the Epic team to complete the task of uploading photos. 

I don't know if Featured Image is hardcoded into Core, this may require a conversation. Feel free to Slack me about it.

S

**Comment by d4mation** [comment]
The Tile field, while it exists on Live, it _not in use on Live yet_.

The fields have been renamed on Staging as part of #140. Once that has been approved, those changes will be brought Live.

**Comment by evasolo** [comment]
It looked to me like they were named tile, featured, and hero.  I assumed
hero went to the top and featured went someplace on the event page and tile
went to tile.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
#140 complete. What do you need to close this out @d4mation ?

**Comment by d4mation** [comment]
This should be fine to close now, as #140 made clear what each field is for: 

![image](https://user-images.githubusercontent.com/7770631/45839945-af554800-bce3-11e8-8d0e-1a1c3adc2cd9.png)
