### ISSUE TITLE
Event Hero Image is not showing in new layout

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_EPIC#155]

**Comment by d4mation** [comment]
Can you link me to the problem?

**Comment by BigActual** [comment]
@marieepicraces and I just tried to add a hero image to an event. We are working in the private event copy of Hot Cocoa Classic, so that you know which event we are having the problem with. We do not want to "Publish" the even until its cleaned up. The assumption is that it's not going to show up when published because it does not show up in the preview view. 

https://epicraces.com/wp-admin/post.php?post=9329&action=edit

**Comment by d4mation** [comment]
This is caused by #140. This should be corrected on Staging.

**Comment by BigActual** [comment]
Are you pushing this change to live now?

**Comment by d4mation** [comment]
The change has not been reviewed yet it seems. Still pending.
