### ISSUE TITLE
Buttons in events for the hero image are not found/fillable

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_EPIC#156]

**Comment by d4mation** [comment]
Is this in the new layout or the old layout? Can you link me to an example?

**Comment by BigActual** [comment]
New. The client called in and could not find the fields to fill in that would generate the Sign-Up and Volunteer buttons. If it's not clear, the buttons are to show right under the Event Title, in the hero image area on event single and will cause the Run Sign Up Widgets to display within an overlay, above the event on the Z Index.

**Comment by d4mation** [comment]
They show directly below the Page Sections fields.

![image](https://user-images.githubusercontent.com/7770631/45835633-a27f2700-bcd8-11e8-878f-95a05b3b94f6.png)

**Comment by BigActual** [comment]
When we've been working on it so closely those titles make perfect sense for us. For the Epic Team, they are clear as mud. Could you please edit the section titles so that they say 'Registration Button' and 'Volunteer Button' instead of just Registration and Volunteer, please?

**Comment by marieepicraces** [comment]
Actually, Steve, clarity is not the problem. I did find those fields in the Hot Cocoa Classic  copy (private page) I'm working on and added what I assumed was the Run Sign Up widgit in the Register Embed field as depicted in the screen shot. This didn't result in any visible registration button from my view.

**Comment by BigActual** [comment]
Thank you for the added information @marieepicraces . We will take a deeper look to see why it did not show in the Event View.

**Comment by d4mation** [comment]
I just tested viewing the Private Copy of the Hot Cocoa Classic and clicked the "Register" button and it worked for me:

![image](https://user-images.githubusercontent.com/7770631/45839623-e4ad6600-bce2-11e8-9169-528bffb1676f.png)

Is it working for you now?

**Comment by marieepicraces** [comment]
It is! Though, it works less well for anyone (like me) already signed into
a RunSignUp account and with multiple registrants attached. A problem for
RSU, though.

I'm now working on the site via the staging platform, rather than creating
private pages.

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by BigActual** [comment]
@marieepicraces, I wouldn't shift at this point. Eric will be pushing changes approved by your team today. None of your content goes from staging to live. Only thematic and programmatic changes.

**Comment by d4mation** [comment]
⬆️ 

To re-iterate, no pages that you create/edit on Staging will transfer over to Live. Only functionality and appearance changes made to Staging will (as they are approved).

**Comment by marieepicraces** [comment]
But Staging seems like a good place to test things as you guys work out the
bugs and push through more changes. Easier for all of us to see, etc


Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
If you're just testing that is fine, we just want to ensure that you know that building out full pages there may be ill advised as you would need to do them over again on Live 👍

**Comment by marieepicraces** [comment]
Yes, until I get those global content blocks working, I'm afraid it's all
testing - thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by BigActual** [comment]
@marieepicraces,
@evasolo is asking about this issue. I see that further up in the thread there is some acknowledgment from you, that the buttons are available, and that they do show the proper information. 

Was this issue finished or did it somehow get closed accidentally? I'm going to reopen it for clarification, but we can close it right back up if it's all set.
