### ISSUE TITLE
Show Past Events Button Not Needed

### ISSUE THREAD

**Issue by marieepicraces** [realbig/RBM_TH_EPIC#157]
Realizing that we don't need the Show Past Events button on the home page, since all of our events show all the time now, via the tiles. 

Thanks!

**Comment by d4mation** [comment]
This has been pushed to Staging. I know this is a pretty small change, but could you please check Staging and confirm that everything regarding this looks good? I'll then get this change pushed Live. 👍

**Comment by marieepicraces** [comment]
Looks good to me - thanks.

**Comment by d4mation** [comment]
This change is now Live.
