### ISSUE TITLE
Testimonials Archive showing Post Author and missing Featured Image

### ISSUE THREAD

**Issue by marieepicraces** [realbig/RBM_TH_EPIC#158]
A few questions:
 - how are testimonials selected for inclusion on the home page?
 - what does the "excerpt" feature do?
 - how can we make the Author disappear? (I obviously didn't write the testimonial - I just added it to the site!)
Please reference this latest addition: https://epicraces.com/testimonial/shanon-lusk/

Thanks for your help.

**Comment by d4mation** [comment]
> how are testimonials selected for inclusion on the home page?

All of them are selected. They are also ordered randomly.

> what does the "excerpt" feature do?

The Excerpt is what shows on the Home Page in the Slider. It is an excerpt of the Main Content. This field lets you type in your own Excerpt rather than have one auto-generated with the first 55 words.

> how can we make the Author disappear? (I obviously didn't write the testimonial - I just added it to the site!)

Where do you see the author? It doesn't show for me when I click that link.

**Comment by marieepicraces** [comment]
Author shows when you click "View all" after Testimonials on the home page. Which goes to this link:
https://epicraces.com/testimonial/

I'm also not convinced all  of the testimonials are being included. When I click the right arrow, I see the same 5-7 cycling through. I've never seen this new one show up. 

Also, where is the featured image?

**Comment by marieepicraces** [comment]
It looks like 10 testimonials cycle through at a time. Not certain there are more than that included on the home page. Thanks for looking into it!

**Comment by d4mation** [comment]
I just tweaked this on Staging, let me know what you think 👍 

> It looks like 10 testimonials cycle through at a time. Not certain there are more than that included on the home page. Thanks for looking into it!

Ah, yes, you're right here. So the way that it works is that it pulls a random 10 form a pool of all of them. They are as a result always in a different order.

**Comment by marieepicraces** [comment]
Is there any way that they could be pulled from chronological order? Or top
10, sense we can reorder them? I feel like the most recent will be the most
relevant, most times....


Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
I just pushed a change for that to Staging. Now they are based on "Menu order" so that you can re-arrange them. It will show the top 10.

**Comment by marieepicraces** [comment]
Really? Because I just added a new testimonial, with photo, to Staging and
I'm not seeing it on the home page. Can you double check?

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
Seems that merging the code into the test branch didn't work properly. Please try again.

**Comment by marieepicraces** [comment]
Looks good in staging. Can you push it Live so that we can try to get them
updated?

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
This is now pushed Live

**Comment by marieepicraces** [comment]
Eric, just based on the testimonials and images we've loaded on the back end, it doesn't seem that the top 10 are loading onto the home page. Can you look into this and let us know what's going on? Thanks.

**Comment by d4mation** [comment]
It seems that the Order was not saved. I found an easier way to order these at this page: https://epicraces.com/wp-admin/edit.php?post_type=testimonial&page=order-post-types-testimonial

Once they are ordered as you would like, you need to click the "Update" button at the bottom and wait for it to say "Item Order Updated". There's no progress bar or anything while it does this, unfortunately, but it goes pretty quickly.

I have hit the "Update" button for you and now it is showing them all in the correct order for me. It must have needed to update the "order" values for all of the Testimonials to force them to be in the correct order.

**Comment by marieepicraces** [comment]
Thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com
