### ISSUE TITLE
Events Menu Ski Listing

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#16]
Hi Kyle! Apparently the "Ski" event category was supposed to be up on our events menu last week. Can you let me know when this will be up? Those ski events are in early January and we need the visibility on our site ASAP. Thanks!

**Comment by AnaHotaling** [comment]
OH! And Eva wants to know if she can email you her approval for issues or if she has to register for Github and send you her approval through Github.

**Comment by brashrebel** [comment]
Thanks for the questions Ana. Eva can provide approval for something any way she likes. Email, phone, text, github, whatever works for her. The only thing we really want to be here in github is actual input about what needs to be done. This is where discussions can happen so if all Eva has to add is "yes, do it" or something like that than she can communicate that directly to me however she prefers.

As for the ski category, we have all the work done on our testing site but have not yet been able to complete a new icon for the ski category. That will be a priority early this coming week. If you don't mind a non-ski related icon being used for a couple days, we can just deploy that work early and add the icon later. Up to you.

**Comment by AnaHotaling** [comment]
Let me check with Eva about the non-ski doodad. I have her on text right now.

**Comment by AnaHotaling** [comment]
Ummmm... did either of us mention to you that these are cross-country ski races, not downhill? I figure I should say something, although I'm one of those out-of-staters who still doesn't think Michigan has much in the way of downhill so of course I meant cross-country skiing! I'm rambling, sorry. Haven't gone to bed yet because I was decorating and wrapping. I personally say use a non-ski. Eva is going to think about it. Maybe take the runner icon and use a drawing utility to slap two sticks on its feet and two sticks into its hands as poles? :D

**Comment by AnaHotaling** [comment]
Eva would like something up there ASAP even if it's just the word "ski" for now. Thanks!

**Comment by d4mation** [comment]
This is all set on the Live site. Once an icon is created for the Ski Menu Item (#8), it will automatically update itself in the Menu.

For Events to begin showing under the Ski Menu Item, Events will just need to be assigned to the "Ski" Event Category.

![image](https://cloud.githubusercontent.com/assets/7770631/12011033/982e7026-ac8c-11e5-805b-00c8310e945f.png)

**Comment by AnaHotaling** [comment]
Excellent! Placement of "SKI" should be beneath Goddess and above Kids. Instead of a blank icon, can an image of the word SKI be used until the actual graphic is ready? Thanks!

**Comment by d4mation** [comment]
How does this look? I have it using the same Blue as Swim.

![image](https://cloud.githubusercontent.com/assets/7770631/12011181/baef38ac-ac91-11e5-8c6d-31ec4fe446e5.png)

**Comment by AnaHotaling** [comment]
That works!!! Thank you!

**Comment by AnaHotaling** [comment]
Not sure how to reopen an issue; we would like to keep this open until the ski graphic is up. Thanks!

**Comment by d4mation** [comment]
The Ski Graphic has its own Issue (#8), but I'll go ahead and re-open this for you.
