### ISSUE TITLE
Social Icons overlapping Event Title

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_EPIC#162]
![image](https://user-images.githubusercontent.com/8271108/45919698-a0979e00-be67-11e8-95cf-0d698ffd4a36.png)

**Comment by d4mation** [comment]
@evasolo Pushed a fix for this to Staging. Can you confirm that it has been corrected, please? I'll then get it pushed to Live.

Here's a Legacy-layout Event that would have been effected: https://epicraces.staging.wpengine.com/event/the-frosty-ski-fest/

**Comment by BigActual** [comment]
Actually, I called this one out. That's the way Joel had it set up. Feel free to push it to live.

**Comment by d4mation** [comment]
Pushed to Live 👍
