### ISSUE TITLE
Detroit Women's Half missing from Home Page

### ISSUE THREAD

**Issue by maryepicraces** [realbig/RBM_TH_EPIC#165]
The event Detroit Women's Half is no longer showing up? Do we need to just add the new date and will it reappear?

**Comment by d4mation** [comment]
Yes, you will have to add the new date and it will re-appear. The site is configured so that 3 days after an Event has passed it falls off the home page. But if a new date is given, it will re-appear.

**Comment by marieepicraces** [comment]
Got it - just updated it so it appears on the home page now, with the date for 2019
