### ISSUE TITLE
Hot Cocoa Classic Age Groups listed twice

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_EPIC#167]
I don't know if it was intentional, so I'm creating this issue for review. On the Hot Cocoa Classic, age groups are listed twice. I believe the second listing is the duplicate information that should be removed.  Feel free to close this if the information is correct.
![image](https://user-images.githubusercontent.com/8271108/46139594-efa15280-c21c-11e8-8d43-d1a48f1e6890.png)

**Comment by marieepicraces** [comment]
Thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com
