### ISSUE TITLE
Epic Contact Us Form

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#19]
Eva has asked me to update the Contact Us form, as it has our old fax and phone numbers on it... I can't find it on the dashboard to edit! Could you please tell me where I would find it? And while I'm here, what exactly are "Features," as listed on the dashboard? I looked in there for the Contact Us form and, since we don't have any Features, I figure I should ask what they are in case we want them at some point!

**Comment by brashrebel** [comment]
@AnaHotaling you should be able to just edit the contact us page [here](http://epicraces.com/wp-admin/post.php?post=1857&action=edit). As for Features, that is a type of content that is not used anywhere on the site currently so I'd just ignore it completely. It came with the theme we started with years ago but we restructured things and no longer include that content type.
