### ISSUE TITLE
Contact Us continued

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#20]
Hello again! Edited the page, but Eva would like the form info sent both to her email and to me at ana@epicraces.com (I am now handling all the emails coming to us from Run Sign Up and she'd like my help with the Contact Us emails from our own site). I'm not seeing how to edit the Contact Us form to include my email so that I also receive any form submissions. Can you help me with this? Thanks!

**Comment by d4mation** [comment]
Just updated the Contact Form to include your email as well as Eva's.

**Comment by AnaHotaling** [comment]
Thanks!!!!!

---

Ana Hotaling
ana@hotalings.com

---
