### ISSUE TITLE
Charity Partners category in template

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#21]
Eva tells me you'd like us to start a new issue for the charity partners. Here it is! We would like "Featured Charities" as one of the sponsor categories. This will allow us to select as many or as few charity sponsors as needed per event, as we currently do with the sponsor levels. Thanks!

**Comment by brashrebel** [comment]
This is the same issue being discussed in #15 I think

**Comment by AnaHotaling** [comment]
Not the same issue as #15. Eva stated you wanted us to open a new issue regarding how to handle the charity partners. Please reopen... and then please show me how to reopen issues that have been closed. Thanks!
