### ISSUE TITLE
Add a Crowdrise widget to the home page to replace where the partners used to be

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#23]
Also from our meeting with Crowdrise yesterday, we will be getting a customized widget displaying all of Epic's fundraising for local organizations. Eva has long wanted to show how Epic gives back to the community, and Crowdrise provided us with this perfect method at the meeting. They are already working on the preliminary widget; the widget will evolve as we add more and more event fundraising through Crowdrise. Eva would like to at least get it started with the Ann Arbor Marathon charity information, however. Crowdrise should have this for us at some point next week, although possibly sooner. The widget will go on the home page, where the sponsors/partners were once displayed. I wanted to get this submitted now, since Eva is going out of the country in a few days and I wanted her to have an idea of what billable time this would involve, since the widget will most likely be ready to implement while she is away. Thanks!

**Comment by brashrebel** [comment]
Acknowledged. Unfortunately, to accurately estimate time, I'll need to know exactly what this is and how it works. Once this is available, please share with us so I can estimate and recommend a course of action.

**Comment by AnaHotaling** [comment]
I'll see if I can get a thorough explanation from Crowdrise for you!

**Comment by AnaHotaling** [comment]
Well, no explanation, but this is the widget... they just sent me the code:

<a href="http://www.crowdrise.com" id="crowdriseStaticLink-event-9993" title="Fundraising Websites on Crowdrise">Fundraising Websites - Crowdrise</a><script type="text/javascript" src="https://www.crowdrise.com/widgets/donate/event/9993/"></script>

It might need some tweaking, but I won't know until I see it implemented. :(

**Comment by AnaHotaling** [comment]
Oh for pete's sake. I guess I am going to email you the code. Sorry!!!

**Comment by AnaHotaling** [comment]
Let me know if you got the email with the code in it... thanks!

**Comment by d4mation** [comment]
Yep, we've got it! That's one of the next things on my list to tackle.

**Comment by AnaHotaling** [comment]
Lists seem endless, don't they? Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races

**Comment by brashrebel** [comment]
In your email @AnaHotaling you mentioned changing some text in this widget. Unfortunately, this can't be done on our site. The widget just pulls data from CrowdRise. Are there settings on CrowdRise for changing the text?

**Comment by AnaHotaling** [comment]
I wouldn't be able to change them... I'd have to tell our Crowdrise reps to change them for me. What a hassle! But I can't tell them how to customize the darned thing until I can see it. Is there any way to see it in a preview mode before it goes live on the site?

**Comment by d4mation** [comment]
Here's how it could look on the Homepage. I threw it below the Events List as an example:

![image](https://cloud.githubusercontent.com/assets/7770631/12209855/d8231d1c-b623-11e5-97e0-ed0332074137.png)

**Comment by AnaHotaling** [comment]
Well. It's not terrible. But it's not great, either. I'll ask if they can make it more horizontal. Any specific dimensions you'd like me to throw at them so it fits in that space at the bottom of the two columns?

**Comment by d4mation** [comment]
You want it to span the two columns? That wouldn't be possible as they are entirely separate from each other. Each one is its own set of Widgets that go down the page vertically, and getting something to occupy space between two wouldn't work.

What we could do is place it within its own row under all three columns. All three columns together are about 912 pixels wide.

**Comment by AnaHotaling** [comment]
Hmmmmm. I was trying to use up that empty space! I just had an idea... let
me run it by Eva, but probably not until this weekend's races are done!
Thanks and have a great weekend!

Ana Hotaling
Director of Inbound Marketing, Epic Races

**Comment by AnaHotaling** [comment]
I'm back. Crowdrise confirmed that any size customization would need to be done on our side. Eva said she is fine with you guys customizing it so it fits tidily into the homepage layout. How much time would we be looking at for this? We might need to modify how Feedback and Upcoming a Events are displayed so everything is neatly tiled.

**Comment by brashrebel** [comment]
@d4mation- can you share your mockup/concept here?

**Comment by d4mation** [comment]
Here it is:

![image](https://cloud.githubusercontent.com/assets/7770631/12403741/f8657916-be03-11e5-9032-12256645480e.png)

On the Right is how it looks on Mobile.

This spans the width of all 3 columns on the Homepage.

We can't do much to the Orange Triangle in the corner since it is an image handled by Crowdrise's Server.

**Comment by AnaHotaling** [comment]
Perfect! And as we get other races set up on Crowdrise, the widget will
have more stuff in it. That is going to be a while from now, though... we
don't have everyone on board for the marathon!

Thanks!

On Monday, January 18, 2016, Eric Defore notifications@github.com wrote:

> Here it is:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/12403741/f8657916-be03-11e5-9032-12256645480e.png
> 
> On the Right is how it looks on Mobile.
> 
> This spans the width of all 3 columns on the Homepage.
> 
> We can't do much to the Orange Triangle in the corner since it is an image
> handled by Crowdrise's Server.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/23#issuecomment-172664713.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races

**Comment by AnaHotaling** [comment]
Crowdrise informs me that the widget is all set to go... can you make it live, please? Thanks!

**Comment by d4mation** [comment]
Just to confirm, you are wanting this below the 3 columns on the Homepage as its own row, correct?

**Comment by AnaHotaling** [comment]
Yes! Just like you showed me... and to get it a little more visible, we
need to cut Upcoming Events so that it only shows 3 events instead of 5.
Thanks!

On Wednesday, February 3, 2016, Eric Defore notifications@github.com
wrote:

> Just to confirm, you are wanting this below the 3 columns on the Homepage
> as its own row, correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/23#issuecomment-179291992.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
All set!

You can access it via:

Dashboard->Appearance->Customizer->Widgets->Homepage Full

and then clicking the one that says "Text".

![image](https://cloud.githubusercontent.com/assets/7770631/12787516/bb035eb4-ca63-11e5-8531-2ab0c019045d.png)

**Comment by AnaHotaling** [comment]
Super!! Thank you!!

On Wednesday, February 3, 2016, Eric Defore notifications@github.com
wrote:

> All set!
> 
> You can access it via:
> 
> Dashboard->Appearance->Customizer->Widgets->Homepage Full
> 
> and then clicking the one that says "Text".
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/12787516/bb035eb4-ca63-11e5-8531-2ab0c019045d.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/23#issuecomment-179303642.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
