### ISSUE TITLE
New category on Homepage

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#24]
Please replace "Clinic" with Virtual.  Also, please change order to:
RUN
TRIATHLON
GODDESS
VIRTUAL
SWIM
BIKE
SKI
DUATHLON
AQUABIKE
KIDS

**Comment by AnaHotaling** [comment]
And don't forget the Ski graphic! :)

**Comment by brashrebel** [comment]
Is Virtual a new category or a new name for the same category?

**Comment by AnaHotaling** [comment]
Virtual is a new category. I also have the graphic that Eva would like to use for the Goddess category. I'll attach it to this comment. Oh wai, Eva sent it as a PDF. I'll ask her for the JPG or PNG.

**Comment by AnaHotaling** [comment]
Say Kyle, is there any way I can get the rights to the Event menu like I have for the navbar? That way, I can rearrange the listings to what ever order Eva wants them to be in. I'm assuming that it's graphic based and just involves dragging into the correct order. I have a feeling that we'll be changing the order again soon, and it would definitely be easier if I could just go in and quickly do it. Thanks!

**Comment by brashrebel** [comment]
@AnaHotaling thanks for the update. I would honestly _love_ to give you control over the events menu. Though at this point I'm not quite sure if we can. That menu is much more complicated than the standard menu and there isn't currently an interface for managing it. It is pretty much all code so if you need to manage it, we'll have to create some kind of visual interface for allowing you to do so. Definitely possible. Also definitely time consuming and would cost something. I don't want to sound like I have keys to something and I'm just not giving them to you. Just that menu is pretty complex so there isn't a way to manage it at all unless you're a pretty capable developer.

**Comment by AnaHotaling** [comment]
Ugh. Darn. I was hoping it was a visual interface. Never mind!

Eva says she sent you the logo in another issue... can you confirm that you've received it?

**Comment by brashrebel** [comment]
Yep, got it and we're good to go for now over there.

**Comment by AnaHotaling** [comment]
Eva sent it in PDF, she says... do you need it in an actual image format? Let me know and I can send it over.

**Comment by brashrebel** [comment]
This will work for now.

**Comment by AnaHotaling** [comment]
Okay, thanks!

**Comment by brashrebel** [comment]
We did look into this a little and I'm confident now that we could make a solution for you. It would take about 2 hours of billable time but in the end we'd be able to give you control over the events nav in a similar way to the main navigation. Does this sound worthwhile?

**Comment by AnaHotaling** [comment]
I'd have to talk to Eva. Just out of curiosity, what scripting language or programming language is used for the Events menu? I'm assuming it's something like PHP or Python...

**Comment by d4mation** [comment]
For the Virtual category, which icons would you want to display on the Menu? The Running, Biking, and Swimming icons like how Clinic showed?

**Comment by AnaHotaling** [comment]
Just the running! We only have virtual runs at this point. I don't think we're even ready to consider a virtual triathlon! :D

**Comment by d4mation** [comment]
All set on your website!

**Comment by AnaHotaling** [comment]
Ummmmm..... neither the Ski or Goddess graphics are coming up. Just little squares with I have no idea what inside them...

**Comment by d4mation** [comment]
Likely a Caching issue on your end. Hard-Refreshing the browser will forcibly load the newer versions of the files from the server.

CTRL+F5 on a Windows computer, or CMD+SHIFT+R on a Mac.
