### ISSUE TITLE
Goddess on Home Page

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#25]
I understand we have a color scheme, but we'd like to have the Goddess be pink: RGB(237,84,141)
We would also like the icon to be an excerpt of our Goddess logo- just one of the wings.  I don't know how to upload on here, but I can send the logo.

**Comment by brashrebel** [comment]
So just to be clear, you're referring to the Goddess event category in the events dropdown in the upper left of every page?

This should take about two hours and I can add it to our queue.

**Comment by evasolo** [comment]
Yes, that is the one.  I have attached the logo to use for the icon. I know it's a pdf- hope you can work with that?
[Epic Offices_GoddessWing.pdf](https://github.com/realbig/RBM_TH_EPIC/files/82869/Epic.Offices_GoddessWing.pdf)

**Comment by brashrebel** [comment]
I'll see what we can do.
