### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#27]
Do we need to continue to have our analytics tied to Runningpromotions with Dave Parham?  Is there a way to change that and remove his access?  We have not relationship at all with him anymore.

**Comment by brashrebel** [comment]
Unfortunately, Google currently offers no utility for simply transferring ownership of a property. We would have done that long ago if such an option were available. The only thing we can do is create a _new_ account and begin tracking with that instead. The old property would still exist but would no longer show new data. We would continue having access to the old data until Dave deletes the account or revokes our access, if that ever happened.

Would you like to create a new account? If you do, then just create a new account in Google Analytics, create a new property and add me as a user to the Account. I'll go from there and make sure that the property is configured correctly, relevant users are added and the tracking code replaces the current one. Up to you. If you have more questions, ask them here.

**Comment by AnaHotaling** [comment]
Good morning! Eva says that she got this started and is waiting for you to go in and configure everything... have you received notification from Google about this?

**Comment by brashrebel** [comment]
@d4mation- can you please ensure that the new tracking code is placed on the site and the old one removed?

**Comment by d4mation** [comment]
The Live Site now uses the updated tracking code!
