### ISSUE TITLE
Tiered staff structure?

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#28]
Good morning!

Eva and I had been discussing having the staff page as a tiered structure, with the central staff at the top and event staff following. Can a separation be made? We actually were talking about this in late December; I only just got around to bringing it up! :)

**Comment by brashrebel** [comment]
Cool idea! Do you have any ideas on specifically how this would be displayed? Just one grid of people with a heading and below that another grid with a different heading? Or do you want any other visual differences? And will it only be the two groups? And will any people appear in both groups?

**Comment by AnaHotaling** [comment]
That's exactly it: one grid of people with a heading and then another grid
with a different heading. No one from Central Staff would be displayed in
Event Staff, even though they all work events. It's more to differentiate
who works full time versus just the races.

Ana Hotaling
Director of Inbound Marketing, Epic Races

**Comment by brashrebel** [comment]
This should take about 1 hour of time for us to implement and we can get it done by next Monday with approval. What we'll do is add some checkboxes for when you edit staff to identify whether someoen belongs in one group or the other. And then we'll modify that page to display them like you've described.

**Comment by AnaHotaling** [comment]
Great! I'll get confirmation from Eva the next time she checks in (she's in
Cambodia on vacation right now). That should be tonight... I think that's
morning for her!

Ana Hotaling
Director of Inbound Marketing, Epic Races

**Comment by d4mation** [comment]
This has been implemented on your site!

As no Staff Members have been assigned to a Tier yet, it looks the same as it did before. Once they are assigned, they will begin to separate into their own Tiers.

![image](https://cloud.githubusercontent.com/assets/7770631/12752506/de88f174-c990-11e5-9749-242cb1e40283.png)

**Comment by AnaHotaling** [comment]
Excellent!!! Thanks!

On Tuesday, February 2, 2016, Eric Defore notifications@github.com wrote:

> This has been implemented on your site!
> 
> As no Staff Members have been assigned to a Tier yet, it looks the same as
> it did before. Once they are assigned, they will begin to separate into
> their own Tiers.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/12752506/de88f174-c990-11e5-9749-242cb1e40283.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/28#issuecomment-178603106.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
