### ISSUE TITLE
Remove "This Event Has Passed" from Detroit Goddess page

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#29]
Directly under the slide show on the Detroit Goddess page, there is a pale blue bar that says, "This event has passed." I checked the dates set for the event, and start and end are both 9/18/2016... not sure why this bar is showing up.

**Comment by d4mation** [comment]
On my Local instance this bug doesn't seem to exist.

Are you still editing that Event, @AnaHotaling? Currently you have control of it and I'd have to boot you off to look into it on the Live site.

**Comment by AnaHotaling** [comment]
Go ahead and boot me off! Sorry... forgot to return to Dashboard!

Ana Hotaling
Director of Inbound Marketing, Epic Races

**Comment by d4mation** [comment]
Should be all good now! I'm not sure why I couldn't reproduce the bug Locally (As it is a mirror image of the Live site), but I updated some settings on the Live site and now everything seems to be working as expected.

**Comment by AnaHotaling** [comment]
Pssst. Because I have nowhere else to ask this, what the heck are the names of the fonts Epic uses again? I knew once, about two years ago...

**Comment by d4mation** [comment]
I did a search through the Source Files and it looks like: 
- Open Sans
- Allerta Stencil
- Merriweather
- Arial
- Droid Sans (Although I couldn't find anywhere that used it)

**Comment by AnaHotaling** [comment]
Allerta Stencil! That was it! I went through Stencil and Stencil Standard (I'm making gift certificates) and those didn't look right at all. THANKS!

**Comment by d4mation** [comment]
No problem!
