### ISSUE TITLE
User activation goes to black screen

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#3]
New user is registered in site admin, they get an email with an activation link, click it and get a page which loads part of the Epic header but nothing else and the account does not activate.

**Comment by joelworsham** [comment]
I'm struggling to find where a user would signup? I tried going to `/wp-login.php` and then clicking register, but that takes me to network signup

**Comment by brashrebel** [comment]
Well that needs to be corrected. Users shouldn't be able to get to the network ever. The workflow I was referring to though was an admin creating a user and that user receiving an email.

**Comment by brashrebel** [comment]
This shouldn't be an issue if #6 gets done.
