### ISSUE TITLE
Creating "Fundraising" tab for the events template

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#31]
Eva asked me to look into this. Could the "Details" tab on the Ann Arbor Marathon page be changed to "Fundraising," or does it have to be an across-the-board template change? If that's the case, how many hours would it take to create a new "Fundraising" tab  on the events template? The Crowdrise widget for each individual race would go here.

**Comment by AnaHotaling** [comment]
Update: Eva would like to go with a separate "Fundraising" tab to join all the others at the top of each event page. I suppose I should ask her what order she'd like the tabs. I'll do that and get the answer to you!

**Comment by brashrebel** [comment]
Thanks Ana. Whatever specific info you can give about where it needs to go, what it links to, what it will look like, will it be the same on every single event, etc. will make it easy for me to estimate time involved and for us to accurately deliver.

**Comment by AnaHotaling** [comment]
Hmmm. I know it will link to the Crowdrise widget for that particular race.
The. Button itself will look like all the other blue buttons at the top;
the crowd arrives which it will look like whatever CrowdRise gives us.
Probably very much like what's being worked on for the homepage. It'll
differ per event. Where on the page it will go... I know Eva wants it
relatively near the slideshow. Not directly beneath it. Would it be
possible to have a cell/block to the right of the template a few graphs
from the top?

On Tuesday, January 26, 2016, Kyle notifications@github.com wrote:

> Thanks Ana. Whatever specific info you can give about where it needs to
> go, what it links to, what it will look like, will it be the same on every
> single event, etc. will make it easy for me to estimate time involved and
> for us to accurately deliver.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/31#issuecomment-175256341.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
I must apologize because, though you've done a great job of explaining, I am still a bit confused:
- If it is different for each event, how is it different? Will any events not have this? Will they look different?
- There are a number of different blue buttons at the top. Can you be more specific about the location of the blue button?
- I don't know what you mean by "to the right of the template". We cannot put anything outside the boundaries that all the other elements on the page are conforming to because it would only be there for users with wide enough screens. It needs to be placed within the main column otherwise we're not being friendly to different screen sizes and it would be almost like saying only people with brown hair can run in our races. But maybe I'm misunderstanding your request.
- I'm also not sure what you mean by "graphs" as a basis for measurement.

Thanks for clarifying!

**Comment by AnaHotaling** [comment]
No problem!

All events will have fundraising. Eva wants everyone to have the ability to
fundraise at our events. Crowdrise is customizing widgets for each of our
events, featuring the charity (or charities) that are a particular event's
featured group (MIOCA for Ann Arbor Goddess, Team RWB for Battle of
Waterloo, etc.). The widgets will look the same other than which group is
featured.

The blue button for Fundraising will go with the Schedule, Gallery,
Results, Lodging, Details, etc. buttons.

Graphs = paragraphs. I'm not sure how to explain this. The Fundraising
widget needs to be near the top of the page because Eva wants it
very visible. It would be within the margins of the page. The closest
approximation is the Ann Arbor Marathon page: where the Epic and CFC logos
are, the way the texts wraps around the image? That kind of positioning.

On Wednesday, January 27, 2016, Kyle notifications@github.com wrote:

> I must apologize because, though you've done a great job of explaining, I
> am still a bit confused:
> - If it is different for each event, how is it different? Will any
>   events not have this? Will they look different?
> - There are a number of different blue buttons at the top. Can you be
>   more specific about the location of the blue button?
> - I don't know what you mean by "to the right of the template". We
>   cannot put anything outside the boundaries that all the other elements on
>   the page are conforming to because it would only be there for users with
>   wide enough screens. It needs to be placed within the main column otherwise
>   we're not being friendly to different screen sizes and it would be almost
>   like saying only people with brown hair can run in our races. But maybe I'm
>   misunderstanding your request.
> - I'm also not sure what you mean by "graphs" as a basis for
>   measurement.
> 
> Thanks for clarifying!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/31#issuecomment-175568693.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
So like _in_ the main content? In that case, perhaps we should give you something so you can just manually place it where you want it. What do you think? If you want it to be automatic, it can't go in that space. It must be in a new container of its own. If you want to add it manually, it can go there and we can make a simple way to insert it.

**Comment by AnaHotaling** [comment]
Would it still link to a Fundraising blue tab/button? If there'sa way to do
all this so that Jane Doe shows up, say, at the A2 Goddess page, clicks the
blue Fundraising tab/button/thingie, and gets taken to that area near the
top of the content, then perfect!

Catch #1: we need to be able to turn it on and off manually, like we do for
the Gallery and Race-Day Guide buttons. Partly because, every year, the
sponsor may change and Crowdrise will need to give us a new widget. Partly
because we are only working on the marathon right now; the rest of the
events' fundraising will fall into place after it is ready.

If it can't be ... oh ugh, let me get to my computer, one sec. Nope, I
don't see how to E corporate a widget that size up at the top, above the
slide show. And it would look awful up there anyway, hitting people up for
$$ immediately.

Ugh.

Okay, if you go to the Waterloo Grit & Gravel event page, where the graphic
of the fat bike is is exactly where this container for the widget would go,
with the text wrapping around the widget (or occupying its space if
Fundraising is not checked.

Oh! Just texted Eva to verify we no longer want the Donate button by
Volunteer and Register if we are doing a Fundraising button instead

On Wednesday, January 27, 2016, Kyle notifications@github.com wrote:

> So like _in_ the main content? In that case, perhaps we should give you
> something so you can just manually place it where you want it. What do you
> think? If you want it to be automatic, it can't go in that space. It must
> be in a new container of its own. If you want to add it manually, it can go
> there and we can make a simple way to insert it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/31#issuecomment-175791434.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
And while I have you here, here is the new order, from left to right, for those buttons/tabs/boxes/links/whatever you want to call them:

Schedule
Venue
Course Maps
Details**
Results
Gallery
Fundraising
Lodging
Sponsors

Details*\* -- there is a possibility that we might want to change this to "Entry Fees" and connect to the pricing table on the template. Waiting for Eva's yay or nay on this. As it is, Details is pretty anemic in information.

**Comment by AnaHotaling** [comment]
Re: "Details" -- Eva just wants it taken out completely. Thanks!

**Comment by AnaHotaling** [comment]
Just checking on how this is going, both for the order of the tabs/buttons and the readiness of the Fundraising button. Thanks!

**Comment by AnaHotaling** [comment]
Moving the re-order of the buttons to its own issue.

**Comment by AnaHotaling** [comment]
Well, just tried plugging in the code for the widget into the Ann Arbor Marathon page and it only came up as a link in Visual, instead of an actual widget. How soon can we get that container going somewhere near the top so the widget can be on the page? We will need this for each of our events. Thanks!
