### ISSUE TITLE
Left padding on pingbacks

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#33]
`.pinglist` could probably at _least_ use some left padding. Pingbacks look pretty terrible right now. [Example](http://epicraces.com/event/sky-tri/#comment-68802).

**Comment by AnaHotaling** [comment]
Is there any way to make a pingback look less spammy? We no longer allow pingbacks on our event pages because they look like spam. Eva was wondering if you could make pingbacks look nice, like regular comments, instead of giant blocks of text from whatever 3rd-party site is being quoted.

**Comment by brashrebel** [comment]
We could look into it. If you have specific ideas on how exactly to accomplish that, please share them.

**Comment by AnaHotaling** [comment]
No specific ideas, other than Eva doesn't want them looking like junk. We
don't ever check off "allow pingbacks." I've asked Eva if we should just
get rid of them.

On Friday, January 29, 2016, Kyle notifications@github.com wrote:

> We could look into it. If you have specific ideas on how exactly to
> accomplish that, please share them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/33#issuecomment-176746543.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Closed in conjunction with #40.
