### ISSUE TITLE
Charity partner content

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#34]
Multiple discussions have been held in the past about the Charity Partner box on single events. I've never really liked the way it looked and also it has never been used as it was designed. Currently it is set up so that the logo of the selected Charity Partner shows up on the left side of the box and the description of the partner shows up to the right. But no descriptions are ever entered so that space is always empty. It was intended that a compelling description of the charity would be included to help explain to visitors why it is such a great cause to support. But right now it's just a plain ol' logo with no explanation.

I recommend that either we redesign this section to not look so silly or start using the description area. @anahotaling, do you have any way to get an answer on this?

**Comment by AnaHotaling** [comment]
I think we are doing away with the charity-partner box and using the
Crowdrise fundraising widget instead. I'll double-check with Eva.

There isn't a place in the template for us to add s description of the
charity partner... all we can do is select who the partner is. 😊

On Wednesday, January 27, 2016, Kyle notifications@github.com wrote:

> Multiple discussions have been held in the past about the Charity Partner
> box on single events. I've never really liked the way it looked and also it
> has never been used as it was designed. Currently it is set up so that the
> logo of the selected Charity Partner shows up on the left side of the box
> and the description of the partner shows up to the right. But no
> descriptions are ever entered so that space is always empty. It was
> intended that a compelling description of the charity would be included to
> help explain to visitors why it is such a great cause to support. But right
> now it's just a plain ol' logo with no explanation.
> 
> I recommend that either we redesign this section to not look so silly or
> start using the description area. @anahotaling
> https://github.com/anahotaling, do you have any way to get an answer on
> this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/34.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
@AnaHotaling understood and that's because you enter the partner's description where the partner is created, not on the event.

**Comment by AnaHotaling** [comment]
Oooh! Got it.

Just heard from Eva actually. It's kill the charity-partner thing and the
Crowdrise widget near the top, as I attempted my best to describe. 😊

And... new order for those blue tabs coming as soon as I can get off my
iPhone and onto my computer!

On Wednesday, January 27, 2016, Kyle notifications@github.com wrote:

> @AnaHotaling https://github.com/AnaHotaling understood and that's
> because you enter the partner's description where the partner is created,
> not on the event.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/34#issuecomment-175783935.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Confirmed just now: Eva wants to scrap the charity-partner area and "work on the fundraising thing. Need to get that up and obvious." Thanks!

**Comment by brashrebel** [comment]
Then let's remove the existing Charity Partner section from the single events template.
