### ISSUE TITLE
Left padding on charity partner section title

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#35]
`h2.epic-charity` needs some left padding. Or center it on the container but I think left aligned is more consistent with the other section titles on the single events template.

**Comment by AnaHotaling** [comment]
No worries... we're killing the Charity Partner section in favor of this new Fundraising section that we're attempting to figure out. :)

**Comment by AnaHotaling** [comment]
Confirmed just now: Eva wants to scrap the charity-partner area and "work on the fundraising thing. Need to get that up and obvious." Thanks!

**Comment by d4mation** [comment]
Charity Partner Area removed as part of #34.

This Issue is all set!
