### ISSUE TITLE
Add warning alert before trashing pages

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#36]
Found out today that, if I click on Trash in a listing of pages, the page immediately gets deleted. If I'd clicked on it by accident (or if my finger slipped while working on my iPad), that would be a very bad thing! Any way to add a "Are you sure you want to delete this page?" alert to give us a chance to go "ACK! Don't delete!" please?

**Comment by brashrebel** [comment]
When you delete a page it will go to "Trash" which you'll see at the top of the lists of pages. You can easily go there and restore any page if you made a mistake. Does this help?

**Comment by AnaHotaling** [comment]
I see that now. How often does the trash get deleted?

On Friday, January 29, 2016, Kyle notifications@github.com wrote:

> When you delete a page it will go to "Trash" which you'll see at the top
> of the lists of pages. You can easily go there and restore any page if you
> made a mistake. Does this help?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/36#issuecomment-176747930.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
After 30 days it will be permanently deleted.

**Comment by AnaHotaling** [comment]
Plenty of time to realize a mistake. Thanks!

On Friday, January 29, 2016, Kyle notifications@github.com wrote:

> After 30 days it will be permanently deleted.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/36#issuecomment-176853926.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
