### ISSUE TITLE
Ann Arbor Goddess page is only half-screen wide in mobile

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#37]
I was checking the price grids this AM due to a participant question. I was on my iPhone because it was "get the kids to school" time. Detroit Goddess was fine, A2 Marathon was fine, but when A2 Goddess came up, it only went across half my screen... except for the embedded video. Could this be due to the color background?
![image](https://cloud.githubusercontent.com/assets/16377404/12677558/dd7a4f0c-c667-11e5-8703-f472f759b029.png)

**Comment by joelworsham** [comment]
For whomever fixes this: Seems that the iframe is pushing the width of the page and needs a `max-width: 100%;`
