### ISSUE TITLE
Scrolling Sponsor Bar not as functional on Firefox as it is on Safari

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#38]
Eva called me to tell me that there was now a scrolling sponsor bar up on the site, to both of our surprises. Eva is on Safari on Macbook; she sees a continually scrolling bar with logos in b/w. I'm on Firefox on Macbook; I see a big empty white space that shows nothing until mouseover. Then I see full-color logos. It doesn't scroll unless I click the side arrows.

Attaching a screenshot.

What are we supposed to see?
![screen shot 2016-01-30 at 3 57 57 pm](https://cloud.githubusercontent.com/assets/16377404/12699476/73b46246-c78a-11e5-80f6-d4071060b180.png)

**Comment by brashrebel** [comment]
Ana,

You are supposed to see this:
<img width="1064" alt="screenshot 2016-01-31 09 42 18" src="https://cloud.githubusercontent.com/assets/4993131/12702735/0444f4dc-c7ff-11e5-8ccf-d18fee6b0e1e.png">

If you've confirmed that refreshing your browser does not fix anything, please let us know as much as you can so we can see if there's a bug. If you want this feature to behave differently, please open separate issues for each individual change. Thanks!

**Comment by AnaHotaling** [comment]
Rebooted my computer and I'm still seeing the sponsor bar as a white, non-scrolling bar that requires mouseovers to see the logos. Will check with Eva about the b/w vs color for the logos.

**Comment by AnaHotaling** [comment]
Started a new issue as requested for how the logos appear. We do want the bar to scroll automatically, which is not happening in Firefox.

**Comment by AnaHotaling** [comment]
Good morning! To get this up to date, the issues are:

Scrolling does not happen automatically on Firefox (checked four computers, 3 Macintosh and one Toshiba)
The sponsor area is a white space until you mouseover; then the logos appear, disappearing when the cursor moves off them.

Thanks!

**Comment by brashrebel** [comment]
I think there's a browser compatibility issue with the method used to change the colors of the images. We'll explore a fallback solution.

**Comment by d4mation** [comment]
Ended up changing how the images displayed entirely to help ensure the best Cross-Browser experience.

I've tested it on my own machine running Chrome, Firefox 44.0, and IE 11.63.10586.0 and everything seems to be working properly now.

**Comment by AnaHotaling** [comment]
Okay... just a note that it doesn't automatically scroll on Firefox. It's
fine on Safari.

On Monday, February 1, 2016, Eric Defore notifications@github.com wrote:

> Closed #38 https://github.com/realbig/RBM_TH_EPIC/issues/38 via aee3297
> https://github.com/realbig/RBM_TH_EPIC/commit/aee3297c11c58fc4dbd7359df2951e1a6d504de8
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/38#event-535021443.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
It should automatically scroll on Firefox.

Are you hovering over any of the images? Doing that restarts the counter
for when it will scroll next.

**Comment by AnaHotaling** [comment]
Yes! We are in business! Works great now. Not sure what happened but it's
good. Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
