### ISSUE TITLE
Logos on Scrolling Sponsor Bar should all be B/W

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#39]
Based on the screenshot of the sponsor bar in the other issue, we would like ALL the logos to be in black and white. It looks like Fraser is in color; not sure which others appear in color. Thanks!

**Comment by d4mation** [comment]
They should all be in black and white until they are hovered over with the mouse cursor. 

@brashrebel was likely hovering over Fraser when he took that Screenshot, and your mouse cursor normally doesn't show when a Screenshot is taken.

**Comment by AnaHotaling** [comment]
Okay... that brings up another thing I'll check with Eva about!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
We're good with them being b/w until mouseover! Closing this out and heading back to the other issues with the scrolling sponsors. :)
