### ISSUE TITLE
Plug-in Installation

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#41]
Eva has asked me to ask you all when the plug-in updates that we keep seeing on the side of the Dashboard are going to be installed. Thanks!

**Comment by brashrebel** [comment]
We take care of those on a routine basis. However, much of the software in use has frequent updates so new notices are almost constant for administrators. I think I will open a new issue for creating a custom role which you can use that won't show such notices since they don't affect you and are just a nuisance.

**Comment by AnaHotaling** [comment]
Okay! I'll let Eva know they're nothing we should worry about. Thanks!

On Friday, February 5, 2016, Kyle notifications@github.com wrote:

> We take care of those on a routine basis. However, much of the software in
> use has frequent updates so new notices are almost constant for
> administrators. I think I will open a new issue for creating a custom role
> which you can use that won't show such notices since they don't affect you
> and are just a nuisance.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/41#issuecomment-180352399.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Taken care of in conjunction with #49. Update notifications shouldn't show for you anymore.
