### ISSUE TITLE
Replace Details Button on Event Page with FAQs Button

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#43]
To go along with this, we will need a sizable text field in the event-page template where all the FAQs for a particular race will be listed. Like the Race Day Guide and the Gallery button, the FAQs button needs to have a check box to activate its visibility. Thanks!

**Comment by d4mation** [comment]
I set this up so that instead of having a checkbox, it will show based on if anything were in the FAQs Textarea for the event or not. The Gallery button seems to be set up the same way.

**Comment by AnaHotaling** [comment]
That works! Thank you!

On Wednesday, February 3, 2016, Eric Defore notifications@github.com
wrote:

> I set this up so that instead of having a checkbox, it will show based on
> if anything were in the FAQs Textarea for the event or not. The Gallery
> button seems to be set up the same way.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/43#issuecomment-179291193.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
