### ISSUE TITLE
Reorganize the order of the blue buttons/tabs at the top of each event page.

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#44]
Please change the order to this:

Schedule
Venue
Course Maps
FAQs
Results
Gallery
Fundraising
Lodging
Sponsors

Thanks!

**Comment by d4mation** [comment]
I'm not sure how often this will happen, but with all 9 Tabs active (with the inclusion of the new Fundraising Tab), things get a bit squished:

![image](https://cloud.githubusercontent.com/assets/7770631/12784346/c0ffb6f0-ca54-11e5-9802-9f706887bf5c.png)

By lowering the font size, we can remedy this issue without losing anything:

![image](https://cloud.githubusercontent.com/assets/7770631/12784384/f7ad7ca0-ca54-11e5-868c-856d32b36a48.png)

Or I can remove the spacing between the Tabs, but then that makes them look a little odd:

![image](https://cloud.githubusercontent.com/assets/7770631/12784410/1b4bce78-ca55-11e5-8eae-2b8e4b2d31fb.png)

I think that lowering the font size is the best solution (It only lowers it to 13px and it is 15px currently), but I wanted to give you the option in case you would rather have the larger font size.

Or if this shouldn't ever be an issue as all 9 Tabs won't be in use at once.

**Comment by AnaHotaling** [comment]
I agree... Even if we just call it Maps instead of Course Maps, the
Fundraising text is pretty darned long.

Plus both FAQs and Fundraising may not be active yet for each event,
depending on what info I've received!!

Thanks!!!!

On Wednesday, February 3, 2016, Eric Defore notifications@github.com
wrote:

> I'm not sure how often this will happen, but with all 9 Tabs active (with
> the inclusion of the new Fundraising Tab), things get a bit squished:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/12784346/c0ffb6f0-ca54-11e5-9802-9f706887bf5c.png
> 
> By lowering the font size, we can remedy this issue without losing
> anything:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/12784384/f7ad7ca0-ca54-11e5-868c-856d32b36a48.png
> 
> Or I can remove the spacing between the Tabs, but then that makes them
> look a little odd:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/12784410/1b4bce78-ca55-11e5-8eae-2b8e4b2d31fb.png
> 
> I think that lowering the font size is the best solution (It only lowers
> it to 13px and it is 15px currently), but I wanted to give you the option
> in case you would rather have the larger font size.
> 
> Or if this shouldn't ever be an issue as all 9 Tabs won't be in use at
> once.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/44#issuecomment-179252801.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
