### ISSUE TITLE
Scrolling Sponsor Bar: Question

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#45]
This got my brain thinking. What is involved in programming/setting something like this up? Is it a widget? I suppose the main point is "Could I do something like this?"

Why I ask is because of the Virtual Goodie Bags. They're okay the way they are, in their presentable little (boring) table. But for one of my races -- I think it was last year's Triathlon Nationals -- they had a scrolling VRB. The participant would go to the VRB page and, in the upper third of the page, the logos of all the vendors in the goodie bag would scroll by in full color. If one of the companies caught your eye, you'd click the logo. The scrolling would pause and, in the middle third of the page, a paragraph would appear with that company's offer. To get the scrolling going again, the participant would click on one of the side arrows. 

Would we be able to do something like this? I'm guessing it might involve a new template -- VRB page perhaps -- or something??

**Comment by d4mation** [comment]
Right now the Scrolling Sponsor Bar is very specific in how it grabs data. It grabs all Sponsors that are marked to be "Featured on Homepage".

For the VRBs, you are talking about [these](http://epicraces.com/shoe-years-day-swag-sneak-peek/), right? To get the result you're wanting, we'd need to implement a few new features into your site that integrates into the Events and re-purpose the code for the Scrolling Sponsors Bar. Basically so that you can enter each one individually similar to Sponsors, and then have the correct ones linked up to the Events.

Or are you wanting to link to a separate page from the Event to show all the VRB information on there?

**Comment by AnaHotaling** [comment]
Sorry! I meant these:
http://epicraces.com/detroit-womens-half-marathon-and-5k-athletes-guide/goddess-racing-virtual-goodie-bag/

Any of our Pages (not Events) that have an event name and "Virtual Race
Bag" in their title. They're very cumbersome.

So we would finally get to use the Features that's in the Dashboard? And
all you'd need to do is wave the magic coding wand and use the code for the
scrolling side bar? And then, if I understand correctly, I would just
select the sponsors who'd be in the VRB and then they'd be in it... plus
the whole click and see the offer and expiration date?

On Thursday, February 4, 2016, Eric Defore notifications@github.com wrote:

> Right now the Scrolling Sponsor Bar is very specific in how it grabs data.
> It grabs all Sponsors that are marked to be "Featured on Homepage".
> 
> For the VRBs, you are talking about these
> http://epicraces.com/shoe-years-day-swag-sneak-peek/, right? To get the
> result you're wanting, we'd need to implement a few new features into your
> site that integrates into the Events and re-purpose the code for the
> Scrolling Sponsors Bar. Basically so that you can enter each one
> individually similar to Sponsors, and then have the correct ones linked up
> to the Events.
> 
> Or are you wanting to link to a separate page from the Event to show all
> the VRB information on there?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/45#issuecomment-179824782.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Any update on this? Submission deadline is coming up for the marathon's VRB, so I'll need to start work on it shortly and it would be nice to be able to do it this way. If it can't happen any time soon, please let me know!

**Comment by brashrebel** [comment]
@AnaHotaling sure. Had to think about this one for a bit. For starters, I agree that there are serious drawbacks to the current layout. Those are:
1. Tables are not mobile friendly. This is basically unusable on a small screen.
2. This is a maintenance nightmare. Creating and managing these pages is surely a miserable time suck. I hate the thought of so much time wasted.
3. The pictures and links are redundant. Those are mostly sponsors who already exist in the site. It seems like a failure to be recreating information that already exists elsewhere on the site.

That said, I may have a difference of opinion regarding how to resolve the above problems. First off, it wouldn't be as simple as just selecting the sponsors since you'll also need to include the offer and expiration which I'm assuming are not the same for every single VRB.

Secondly, I believe a layout similar to what you have now is superior to a carousel. Those are very problematic for many reasons and I would strongly encourage you to use them very sparingly. Despite the fact that you and I have little trouble with them, many other people do. They are very inaccessible to people using alternative viewing technology, slow and very inefficient. If someone wants to view all the offers quickly, your current layout works but a carousel definitely does not. It would take someone far more time to quickly click through a carousel to see every offer then it would be to just scroll. On top of that, you're describing an experience that is unique to this part of the site so it would introduce another inconsistency.

Would you be ok with us simply implementing a system where you can select the sponsors then enter the offer and expiration for each? We'll make it automatically look like it does now (or maybe a bit nicer) and be responsive. This would take about 3 hours. We could get it done next week.

**Comment by AnaHotaling** [comment]
Ha ha! You made me laugh. Yes, creating these tables do take up some
time... but not as much time as me trying to get sponsors to buy space in
the virtual race bags!

And I totally agree that these tables are NOT mobile friendly.

And yes, a number of the VRB participants are sponsors and exist on the
site elsewhere. The title and presenting sponsors get free VRB submissions,
so they appear there... when they bother to submit something, that is!

And you're correct, the offer and expiration date change with every VRB
bag. Except for when they don't (we had one sponsor run the same VRB offer
for the entire year last year).

Carousel is the word of the week! I learned about Instagram and Facebook
carousels yesterday. I should have figured out that was the term for these
automated slide shows!

Ahhh. I see what you mean. Yes, I can see my mother on her eMac attempting
to view the carousel and having immense difficulties. Then again, we are
talking about a woman who calls me because she doesn't remember how to copy
files. Assuming the older participant target audience is like my mom, I get
what you're saying. Darn. It looked like such a nifty idea, too, but if
it's only for the marathon... and even if it weren't only for the marathon.
Hmmmmmmmmm...

Before I go ask Eva to okay the VRB three hours, here's a thought (scary):
what about something like the staff page? Without the tiered structure, of
course. That would be easily viewable! Instead of staff photos, it could be
the logos. Instead of the staff name, it could be the company name (linked
to their site). Instead of the staff bio, it would be the description of
the offer. Instead of the staff title, it could be the expiration date.
Would something like that work?

The one thing to consider, though it that this would be for the basic
submission. There are four levels of VRB submissions, sold at different
rates. A VRB company can pay extra to get a whole heap more text content
about their offer. Or a larger graphic. Or both. Let me see if I can find
the Pistons thing we needed to do last fall.

Here's the link:
http://epicraces.com/detroit-womens-half-marathon-and-5k-athletes-guide/goddess-racing-virtual-goodie-bag/detroit-pistons-women-run-the-d-special-offer/

For a few of the sponsors, we had to create a link from their basic VRB
submission in the table to a separate page that accommodated the extras
they paid for. We'd still need to be able to do something like this.

But I do like the idea of being able to just click on a sponsor and then
input the offer and expiration date. I'm assuming that I'd have to input
each company in the Partners section, right?

Anyway, let me know what you think of doing something like the staff page
for the VRB, and then we'll brainstorm more (or I'll just nod my head and
go, "Ugh, didn't think of that!" and then I'll shoot an email or text to
Eva and ask.Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
Ok, great. So regarding your layout idea, visual changes like that have only a minimal impact on the time it takes to get the work done for us. If we lay it out like a table the way it is (only make it responsive) or whether we lay it out like the staff page makes little difference. However, the concept of separating the presentation into tiers which somehow look different does complicate things a little more. We'd have to build in the logic and options for you to select which partners get which tier for each VRB and make sure they all automatically list in the right order with the right info in the right places.

This change means I'll have to adjust the task to 3.5 hours. Sorry.

**Comment by AnaHotaling** [comment]
Okay! I'll let Eva know. :) Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Eva says this is reasonable and go ahead!

**Comment by d4mation** [comment]
Could you explain further about the different levels of VRB subscriptions for me, @AnaHotaling?

> There are four levels of VRB submissions, sold at different
> rates. A VRB company can pay extra to get a whole heap more text content
> about their offer. Or a larger graphic. Or both. Let me see if I can find
> the Pistons thing we needed to do last fall.

Are you wanting them to be separated based on that in a tier-like structure? We could add toggles for larger image and stuff if you'd like. But with the current layout and the layout based on the Event Staff Page it seems to work best when the images are about the same size.

Here's some screenshots of what I've got working right now. I decided to implement both a responsive version of the Table layout that you have now and one more similar to the Staff Events Page. The layout can be switched on your end via a toggle, so whichever layout you like best for a certain VRB page can be used.

Table layout:
![image](https://cloud.githubusercontent.com/assets/7770631/13793451/4fca48bc-eacd-11e5-8432-1a8e7c171cd7.png)

The Table Layout on Mobile:
![image](https://cloud.githubusercontent.com/assets/7770631/13793532/ac3ae386-eacd-11e5-96cc-4ff61aef93d2.png)

Event Staff-based layout:
![image](https://cloud.githubusercontent.com/assets/7770631/13793475/68c655cc-eacd-11e5-8d4a-d8b29c446d52.png)

And you would add them just like this:
![image](https://cloud.githubusercontent.com/assets/7770631/13793498/81cd886a-eacd-11e5-88ab-21363bd6d6fa.png)

**Comment by AnaHotaling** [comment]
Oooh! That looks GREAT!!!!

The different tiers for the VRB:

Basic, where everyone is the same!

Enhanced Text: a Basic whose company wanted to say lots more about
themselves. They have 1,200 characters of extra space.

Enhanced Graphic: a Basic whose company wanted to include a coupon or
created an ad graphic specifically for our use. Some are enormous, like the
one from the Detroit Pistons. Some aren't that much larger than their logo.

Double Enhanced: A Basic that wants both more graphic space and more text
content.

Not sure what would be the best way to handle these. Right now, I just have
a link to a separate page specifically created for that VRB sponsor. I am
not thrilled with that option, though, so I'm open to anything you can
devise!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I've done some work getting Tiers working with this. 

I've made it so that all of the "Enhanced" Tiers get their own Row, as that seems to fit on-screen best. Especially with the Image and Double Enhanced Tiers, as you have the images to worry about.

They currently output on-screen in this order:
1. Double Enhanced
2. Image Enhanced
3. Text Enhanced
4. Basic

There are no dividers between them right now. I wasn't sure if you'd want headings above them denoting the Tiers or not.

Here's some examples of how the different Tiers look currently:

Double Enhanced:
![image](https://cloud.githubusercontent.com/assets/7770631/13818406/203f1650-eb6c-11e5-8b15-8e6876873961.png)

Image Enhanced:
![image](https://cloud.githubusercontent.com/assets/7770631/13818816/c190bef4-eb6d-11e5-81c4-faaddef481bb.png)

Text Enhanced:
![image](https://cloud.githubusercontent.com/assets/7770631/13818498/6c2a2866-eb6c-11e5-89e2-7667664b6ca0.png)

The Basic Tier looks like the screenshots I sent yesterday and they are still dependent on that Radio button for choosing the Layout.

Here's an updated look at the Edit interface:
![image](https://cloud.githubusercontent.com/assets/7770631/13819038/885307b8-eb6e-11e5-8106-b621ad283735.png)

If anything needs tweaked, let me know!

**Comment by AnaHotaling** [comment]
Looks good to me!!! THANKS!!!! So it's all set to go? Where would I find
this? I have to put together the marathon's VRB on Monday... perfect time
to test it out!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I just now pushed the changes to your Live website! All the screenshots from before were from a local copy that I've got on my work computer. Sorry that that wasn't made clear!

All you would need to do is go to one of your VRB Pages and change the Page Template to "Virtual Goodie Bag" like so:
![image](https://cloud.githubusercontent.com/assets/7770631/13822402/df0ff3e2-eb7b-11e5-95de-24520b00d5b2.png)

Then the settings that I showed you earlier will appear automatically.

Let me know if you run into any problems!

**Comment by AnaHotaling** [comment]
Woohoo! This is going to be fun! Thanks so much, Eric! Let me go do that
with Waterloo Grit and Gravel right now!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
I'm clicking Sponsor -- it's a skinny oval thing -- and nothing is
happening...???

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
That is likely due to some cached files. I had to modify some old code on your site to get those working properly.

A good ol' hard refresh should take care of it. Sorry about that!

**Comment by AnaHotaling** [comment]
ACK!!! HELP!!!!!!

I have no idea where that MI-HQ logo came from. I certainly didn't select
it... I couldn't select sponsor logos!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I have it currently set up to use the Sponsor Logo that is associated with the Sponsor within its Entry in "Partners".

![image](https://cloud.githubusercontent.com/assets/7770631/13828336/669effe0-eb97-11e5-90f5-2de1213f6424.png)

Should I add a separate field so you can specify a different Logo?

**Comment by AnaHotaling** [comment]
Yes, but Mi-HQ isn't even in any goodie bags. They're providing a dumpster
for the Ann Arbor Marathon and that's it. No idea how they got in there,
never mind the multiple times they got in there!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I just checked the VRB you are editing right now and you've got the Sponsor Column to set "MI-HQ" for each of the Goodie Bags.

![image](https://cloud.githubusercontent.com/assets/7770631/13828440/e1b36c48-eb97-11e5-9da2-b3d11886dd2d.png)

Once you've set those to the proper Sponsors it should work just fine.

**Comment by AnaHotaling** [comment]
Oh, I see!!! It's because it defaulted to them as the last Partner I added!

I've sorted that out... what do I do for things we are sponsoring
ourselves? Epic always puts something into the goodie bags, and the Ann
Arbor Marathon has something in there, too... but neither are technically
"sponsors" since it's us.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I know Epic has its own entry within "Partners" that you could use. All the it grabs from "Partners" for the Goodie Bags are the:
- Partner Name/Post Title
- Logo/Featured Image
- Partner's Website

For the [Goddess Racing Virtual Goodie Bag](http://epicraces.com/detroit-womens-half-marathon-and-5k-athletes-guide/goddess-racing-virtual-goodie-bag/) you had Epic listed as a Sponsor, so I figured that selecting yourself via that dropdown would work fine.

You could add a Parters entry for the Ann Arbor Marathon similarly and just use it for Goodie Bags. As far as I've been able to tell, the Partners entries are only used for:
- The Partners Slider, which they need to be set to be within via the "Featured on Homepage" option
- [Events pages as Sponsors/Partners](http://epicraces.com/event/ann-arbor-goddess-5k/)
- And now, for Goodie Bags

It shouldn't cause any problems doing that.

**Comment by AnaHotaling** [comment]
Okay! I added the race logos in under Partner. I then switched to Table
Mode. Can you go take a look? The expiration dates seem to be sitting right
on top of the name of the next VRB sponsor...

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
It was like that for me until I hard refreshed just now. I had to add a fair amount of styling to support these new features ;)

**Comment by d4mation** [comment]
The Edit interface calls for different files than the frontend of your website, which is why you'd need to hard refresh a second time.

**Comment by AnaHotaling** [comment]
Almost there! Just one last question!

On a regular page, when I add media, specifically a graphic, I ca choose
its size: thumbnail, small, medium, large, full size, custom. Any way to
incorporate that here? I'm just lucky enough to get the sponsors to submit
JPG and PNG files (I get PDF, AI, EPS, TIF, you name it). To specify actual
size parameters would be waaaaaaay beyond what we can hope for.

So right now, we have a wide variation in the sizing of the logos. The Epic
logo is teeny, the marathon one is large... any way to be able to add
sizing?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Working on finding a solution right now. The Epic logo in particular is a mere 109x130 at full size, which complicates things.

I don't think providing a height and width field would be the best way to solve this as each logo has its own proportions. It would be easy to accidentally squash a logo that way.

What I could do is provide a maximum height and then have things proportionally scale to meet that like I did for the Scrolling Sponsors Slider. The images there are only able to get to 250px tall and then scale to fit that height.

**Comment by AnaHotaling** [comment]
That would be perfect!

On Thursday, March 17, 2016, Eric Defore notifications@github.com wrote:

> Working on finding a solution right now. The Epic logo in particular is a
> mere 109x130 at full size, which complicates things.
> 
> I don't think providing a height and width field would be the best way to
> solve this as each logo has its own proportions. It would be easy to
> accidentally squash a logo that way.
> 
> What I could do is provide a maximum height and then have things
> proportionally scale to meet that like I did for the Scrolling Sponsors
> Slider. The images there are only able to get to 250px tall and then scale
> to fit within there.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/45#issuecomment-197861427

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I have made it so Sponsor Logos should scale better. Logos that are more landscape-oriented will overall be a little larger, but now things look more uniform.

![image](https://cloud.githubusercontent.com/assets/7770631/13848608/f5ccba18-ec28-11e5-951f-b620eb89009c.png)

These changes are Live on your site and you will need to hard-refresh to see the changes.

**Comment by AnaHotaling** [comment]
Perfect!!!! Thank you so much!!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
No problem!
