### ISSUE TITLE
FAQs are a mess! Priority!

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#48]
Just put in the FAQs for the Ann Arbor Marathon, and even though they are spaced as Q&A pairs, it's just one giant run-on sentence. This obviously doesn't work... people need to be able to quickly browse and locate the question they are asking and its answer.

**Comment by d4mation** [comment]
Fixed!

**Comment by AnaHotaling** [comment]
Thank you!!

On Thursday, February 4, 2016, Eric Defore notifications@github.com wrote:

> Fixed!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/48#issuecomment-179835653.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
