### ISSUE TITLE
New site manager role

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#49]
I'd like to add a custom role for users who don't actually need full administrative privileges. We'll call it site manager and assign Eva, Ana and Richard to this role. We can discuss the specific caps needed.

**Comment by d4mation** [comment]
This has been taken care of in a separate plugin, so that it can have activation/deactivation hooks without being tied to the Theme.

**Comment by brashrebel** [comment]
And the users have been assigned those roles?

**Comment by d4mation** [comment]
Yep! They're assigned. I used @joelworsham's Role Quick Changer plugin to test it locally, so it should include any capabilities they need.

**Comment by brashrebel** [comment]
Users with this role need all caps for all content types. They're apparently not included so I temporarily changed Ana back to an admin.

**Comment by d4mation** [comment]
Added

`moderate_comments`
`manage_categories`
`manage_links`

As well as all the Custom Caps used for The Events Calendar and Gravity Forms. The Events Calendar must have faked me out before as apparently with the `post` Capability Type you still see it on your Dashboard.

Ana is still an Admin for now. I figured we could leave this open until we are able to ensure she has access to everything she needs.

**Comment by AnaHotaling** [comment]
Not sure what the choices are.... Admin and what else is there? Sounds like Site Manager might be a bit limiting for what I need to do.

**Comment by d4mation** [comment]
The Site Manager Role is a custom one we're making for you. Since you last were assigned to it, I've added a fair amount of permissions to it so it should hopefully cover everything that you need. If not, we can always tweak it more.

We can set your User Account to Site Manager whenever you'd like and if it is missing anything, we'll figure out what that is and fix it for you.

**Comment by AnaHotaling** [comment]
Awwww, now you're making me feel all special! :)

On Wednesday, February 17, 2016, Eric Defore notifications@github.com
wrote:

> The Site Manager Role is a custom one we're making for you. Since you last
> were assigned to it, I've added a fair amount of permissions to it so it
> should hopefully cover everything that you need. If not, we can always
> tweak it more.
> 
> We can set your User Account to Site Manager whenever you'd like and if it
> is missing anything, we'll figure out what that is and fix it for you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/49#issuecomment-185193102.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
It's no problem at all! It helps keep your Dashboard clean and gets things you don't need out of the way.

Whenever works for you we can swap your User Account to this new Role, and if there are any hiccups we'll address them. However, I think this time around we've squashed all the bugs. (Like the ones you encountered in #52)

**Comment by AnaHotaling** [comment]
Sure... might as well go for it. If there's anything that I suddenly don't
see that I need, I'll let you know!

Still haven't had a chance to play with the selected themes. Oh! And you
can always say WYSIWYG. I know what that means! :D

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Alrighty, I've swapped you over to a Site Manager. If there's anything that doesn't work correctly, let me know!

**Comment by AnaHotaling** [comment]
Thank you!!!

On Thursday, February 18, 2016, Eric Defore notifications@github.com
wrote:

> Alrighty, I've swapped you over to a Site Manager. If there's anything
> that doesn't work correctly, let me know!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/49#issuecomment-185708650.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
