### ISSUE TITLE
Mobile sponsor scroll bar jumbled

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#50]
The logos are stacking on top of each other... or only show up partially, with the rest offscreen.

**Comment by d4mation** [comment]
I had the same issue just now, until I cleared the Cache on my Nexus 5.

Looking at your screenshot in #51, it seems that you have an iPhone. 

You're going to be looking for:

Settings->Safari->Advanced->Website Data->Edit

To clear the Cache for http://epicraces.com

**Comment by d4mation** [comment]
Just double checking, did this get solved on your end with #51?

**Comment by AnaHotaling** [comment]
It's good! Thanks!!!

On Wednesday, February 10, 2016, Eric Defore notifications@github.com
wrote:

> Just double checking, did this get solved on your end with #51
> https://github.com/realbig/RBM_TH_EPIC/issues/51?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/50#issuecomment-182398928.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
