### ISSUE TITLE
Width on page display in mobile is off agsin

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#51]
This time, it's the Pi Run. See screenshot. 
![image](https://cloud.githubusercontent.com/assets/16377404/12856220/ca9b4198-cc11-11e5-9086-b3ac440ab69a.png)

**Comment by d4mation** [comment]
This seems to have been caused by the arrows on the Sponsors Slider trying to escape off the side.

I moved them to below the Slider for the Mobile Layout. If you clear you cache on your iPhone this should fix the issue.

**Comment by AnaHotaling** [comment]
What a bunch of junk! I've cleared out Epic, plus a whole heap of sites
that I've never even heard of. It works fine now. Thanks!

On Friday, February 5, 2016, Eric Defore notifications@github.com wrote:

> This seems to have been caused by the arrows on the Sponsors Slider trying
> to escape off the side.
> 
> I moved them to below the Slider for the Mobile Layout. If you clear you
> cache on your iPhone this should fix the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/51#issuecomment-180534692.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
