### ISSUE TITLE
Logged in but cannot delete comment

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#52]
I just logged out and logged in again because there's a spam comment on the Detroit Goddess page. When I go to view it, none of the admin options (Approve, Spam, Reply, etc.) come up so I can't get rid of it.

**Comment by AnaHotaling** [comment]
Update: I can't edit any of the events any more. Looks like my admin rights went kablooie again.

**Comment by AnaHotaling** [comment]
![screen shot 2016-02-07 at 11 12 04 am](https://cloud.githubusercontent.com/assets/16377404/12873481/c9cfbc1e-cd8b-11e5-878c-a0708e17a9a1.png)

**Comment by brashrebel** [comment]
You should be all set now. We made a temporary change to your role on the site and I've reverted that for you until we make some key adjustments.
