### ISSUE TITLE
Customization needed for "Important Info" field

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#53]
At last, it's time to use the Important Info field. There are myriad reasons why I need to bring it into play; let's sum it up as I really would rather not spend the rest of my life in a penitentiary. 

Any way, to ensure that this doesn't happen, I need to be able to customize what goes into that Important Info field. Specially, on the Ann Arbor Marathon page, I need to bold "Ann Arbor Residents" and I need to be able to make the posted link active. 

Very loooooooooong story about why it has to be like this. Let's just say it needs to be done to make one of Epic's partners happy and leave it at that. But you can picture me in an orange jumpsuit if if helps.

**Comment by d4mation** [comment]
I just made that field into a "What-You-See-Is-What-You-Get" editor, so now making text bold or adding links should be easy to do for the Important Information field.

I went ahead and took care of these changes for the Ann Arbor Marathon as well.

**Comment by AnaHotaling** [comment]
Thank you!!!!

On Wednesday, February 17, 2016, Eric Defore notifications@github.com
wrote:

> Closed #53 https://github.com/realbig/RBM_TH_EPIC/issues/53.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/53#event-553525377.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
