### ISSUE TITLE
Possibiity of Pop-Up Boxes

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#55]
So, we have this page, Meet the 2016 Probility Ann Arbor Pacers. Our pace-team organizer went a weeeeeee bit overboard and, instead of us having 29 - 30 pacers, we have more than 70. Each pacer is supposed to have his or her bio, telling runners about themselves. What is the possibility of creating a pop-up box/window per name? A person clicks on the name and just the pop-up box opens, instead of a new tab or a new window. I've coded this in the past by hand in html, but I don't know whether Word Press would allow this or not. Please let me know! Thanks!

**Comment by brashrebel** [comment]
Definitely possible. Of course, there's many other ways that this problem could be solved. I'm not a fan of developing custom functionality that is only applicable to one small part of the site and is not consistent with the rest but it is certainly an option. At least I'd like the conversation to focus first on what the problem is and then we can discuss what the best solution would actually be. It could be pop-up boxes but I think discussion needs to take place first.

I'm assuming the problem is that the page would just be too big and daunting if everyone's bio information was inline? Is that correct? So you're looking to make the page more manageable and easier to consume by only revealing bios when users want to read them?

**Comment by AnaHotaling** [comment]
Yes! Exactly what you said in the second paragraph. I'm wide open to ideas.
Each pacer will have a small photo and a short bio. Times 73, that's a lot
of content!

On Monday, March 7, 2016, Kyle notifications@github.com wrote:

> Definitely possible. Of course, there's many other ways that this problem
> could be solved. I'm not a fan of developing custom functionality that is
> only applicable to one small part of the site and is not consistent with
> the rest but it is certainly an option. At least I'd like the conversation
> to focus first on what the problem is and then we can discuss what the best
> solution would actually be. It could be pop-up boxes but I think discussion
> needs to take place first.
> 
> I'm assuming the problem is that the page would just be too big and
> daunting if everyone's bio information was inline? Is that correct? So
> you're looking to make the page more manageable and easier to consume by
> only revealing bios when users want to read them?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/55#issuecomment-193242787.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Hey there! I should be ready to go with the data for these sections by Friday... I still have 48 to edit. Any update as to what wonderful suggestions you have so I don't spend all weekend doing this? Not that I could, with the Pi Run this weekend...

**Comment by brashrebel** [comment]
I'll brainstorm with @d4mation- and suggest something. We have a lot on our plates this week so I'm not sure we can squeeze it in. I'll let you know.

**Comment by AnaHotaling** [comment]
Please do.... I'm supposed to have these up ASAP! Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
A couple questions:
1. Will this problem happen again and be needed on any other pages? Or is this really a one time thing?
2. What about the layout/functionality of the Staff page? These are all people too so what if it worked like that?
3. Are all these people 100% unique to this particular event or are they likely to show up elsewhere on the site ever?

Thanks!

**Comment by AnaHotaling** [comment]
I am hoping that we will NOT do this again for any other event! We were
only expecting perhaps 28 to 30 pacers total... not 73! We may have a Meet
the Pacers for the Detroit Goddess, but it would not be to the scale that
the Marathon is doing it. It's my belief that we will be a little more
strict on how many pacers we will have for future marathons.

The staff page works great for the staff... but I'm not sure if it would
work for this. Take a look at
http://epicraces.com/ann-arbor-marathon-pacing-information/meet-the-2016-probility-ann-arbor-marathon-pacers/.
Participants need to see their estimated/hoped-for pace time, then check
the distance they're running to see who the pacers are. The idea is to
click a name and a window would pop up with that person's photo, their
hometown, the number of marathons they've run, the name of their favorite
marathon, their personal running goals, their strategies for the race,
their social media user names, and their favorite cartoon character. And I
get to make that all as concise as possible from the tomes these people
have submitted. And that's whittling down the number of questions we
originally had!

These pacers are people I have NEVER heard of before. Except for me. They
might some day pace for another Epic event, but if I haven't encountered
them before... for all intents and purposes, it's just for this event, this
year.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
Ok, what I think we'll need to do is make a Pacers content type so you can edit and publish pacers individually. We'll have to add in all the fields you mentioned and create a simple method for you to output them on a page in the list format with some kind of option to click and view the bio/extended info.

This will take us about 12 hours to do and we can have it done in two weeks.

**Comment by AnaHotaling** [comment]
ACK! No, that won't work. We need this out by Monday! Nuts. I guess that
it's just going to be endless pages, one per pacer, then. Phooey. Thanks
anyway!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
No problem. And sorry about that. We need quite a bit more notice for new feature development as a general rule.

**Comment by AnaHotaling** [comment]
Understood! I just thought since I could code the pop ups in HTML, it might
be an easy-peezy thing for you guys. Darned WordPress limitations!

Moving along! :)

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
