### ISSUE TITLE
Correct "Athelete's"

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#56]
Yes, this has driven us nuts long enough! Could you pretty please correct the spelling of "Athelete's" to "Athlete's" in the template for our event pages? Thanks!!!

**Comment by d4mation** [comment]
I couldn't find this misspelling in the Template for the Event Pages, but I was able to find it on the "Show Athlete's Guide" field. Was that the misspelling you were talking about? I have gone ahead and fixed it.

![image](https://cloud.githubusercontent.com/assets/7770631/13670344/50eb33c6-e697-11e5-8a72-7ff1b1d4e4d3.png)

**Comment by AnaHotaling** [comment]
Yes, that's it! Thanks!

On Thursday, March 10, 2016, Eric Defore notifications@github.com wrote:

> I couldn't find this misspelling in the Template for the Event Pages, but
> I was able to find it on the "Show Athlete's Guide" field. Was that the
> misspelling you were talking about? I have gone ahead and fixed it.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/13670344/50eb33c6-e697-11e5-8a72-7ff1b1d4e4d3.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/56#issuecomment-194834509.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
