### ISSUE TITLE
Tracing an contact-form submission

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#57]
Any way to regenerate an email sent through the contact form to us?

**Comment by brashrebel** [comment]
Nope. For future purposes we could log the responses in the dashboard though. That'd require about an hour of work I think.

**Comment by AnaHotaling** [comment]
That's okay! All this person's questions could be answered on the web site.
All she had to do was read!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
