### ISSUE TITLE
Migrate to single install

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#6]
I'd like this site moved to the `epicraces` install instead of on this network. Once completed, the `realbigraces` install can be deleted permanently.

**Comment by d4mation** [comment]
Migration is complete. With my user permissions for WP Engine I'm unable to delete the install, but the domain and such is remapped.

Going to go ahead and close the issue.

**Comment by joelworsham** [comment]
:beers:

**Comment by joelworsham** [comment]
I think my user account got migrated as a subsciber. Can you make sure I'm an admin?

**Comment by d4mation** [comment]
Hm, that was weird. You had NO role assigned. You're an admin now.

I'll double check for everyone else. Probably a weird multisite->single install quirk. I used `wp_insert_user()` to create my account after-the-fact as I didn't have a user and the user activation wasn't working.

**Comment by joelworsham** [comment]
Roger. Probably was role super admin or something. Thanks for upgrading me! I've always wanted to be an admin.

**Comment by d4mation** [comment]
Haha, yeah. That's most likely it.

Seems every other user on the install (Aside from us) is also lacking a Role. Looking at the old Database, some should be things such as Shop Manager.

I'll figure out a way to parse through this and get it all fixed.

**Comment by joelworsham** [comment]
Super. I've had this happen to me in the past. Turns out going from single -> multisite is cake, but doing the reverse isn't so fun.

**Comment by d4mation** [comment]
User Roles are all fixed. I wrote a quick Sub Query and ran it on the old Database to grab each user's Login from `wp_users` based on their ID paired with a Role in `wp_usermeta`.

**Comment by joelworsham** [comment]
:+1:
