### ISSUE TITLE
Drag to arrange the VRB template

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#62]
I'd like to be able to drag the separate entries into the order I'd like for them to appear. Case in point: I created an entry for Dart for Art between Babo Market and Fifth Third Bank... only to realize they go by Ann Arbor Mile - Dart for Art. Now they're out of alpha order! I couldn't figure out how to drag Ann Arbor Mile - Dart for Art past Babo Market and Ann Arbor Running Club, though...

**Comment by d4mation** [comment]
You are able to rearrange them by moving your mouse to the left where the numbers are, and clicking and dragging them as needed.

Your cursor should turn into a 4-way Arrow when you're hovering over the right section.

**Comment by AnaHotaling** [comment]
There are numbers??????? Geez, I must be blind!!!!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Well, what do you know!! :)

Thanks!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
