### ISSUE TITLE
Remove Charity Partner pull-down and section from event-page template

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#67]
Eva and I thought that this had already been removed in favor of the Fundraising button and the Crowdrise widget area. Can this be taken out, please?

**Comment by d4mation** [comment]
To clarify, you mean this guy right here?

![image](https://cloud.githubusercontent.com/assets/7770631/14931632/f1987c14-0e3a-11e6-8beb-d71d252dadff.png)

**Comment by AnaHotaling** [comment]
Yep, that guy right there!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
All set!
