### ISSUE TITLE
Need to edit the descriptive content on the Contact Us Form

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#69]
I can't find where to access this on the Dashboard in order to edit it. Can you point me in the right direction? Thanks!

**Comment by brashrebel** [comment]
We don't currently have a feature developed which will allow you to edit that form. We could modify it so that you could edit it but it would take a couple hours of our time. What would you like us to do?

**Comment by AnaHotaling** [comment]
Checking with Eva...

On Wednesday, May 4, 2016, Kyle notifications@github.com wrote:

> We don't currently have a feature developed which will allow you to edit
> that form. We could modify it so that you could edit it but it would take a
> couple hours of our time. What would you like us to do?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/69#issuecomment-216949025

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Eva says to hold off on this since we have lots of other priority things to
deal with, and we'll get back to this. Question: can I give you the content
to swap out?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
Sure. I'll just send an invoice over after for however long it takes us to implement. If your instructions are clear it should be pretty quick.

**Comment by AnaHotaling** [comment]
Ack! Eva is trying to avoid an invoice... that's why she wanted it tabled
for now. But people are using the form to contact us and ask us questions
that are answered in detail in the FAQs and in the Race-Day Guide of each
event. We just want to edit the paragraph at the top of the form to tell
people to go there first to if they have questions, THEN as contact us. I
guess it can wait!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
Well if that's all you need then you can edit that page [here](http://epicraces.com/wp-admin/post.php?post=1857&action=edit). I thought you needed something more complicated.

**Comment by AnaHotaling** [comment]
I'll wait until you're done editing in there... don't want to take over and
kick you out!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Done! Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
