### ISSUE TITLE
Countdown Clock No Longer Automatically Advances

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#70]
The countdown clock on the site (under Appearance -> Widgets on Primary and Homepage no longer automatically advances to the next event when one is complete. Actually, it hasn't done this for months; I've had to manually go in and advance the clocks. For instance, instead of going to Sky Tri once Ann Arbor Goddess was completed on Sunday, the countdown clock went to the 2017 Ann Arbor Goddess. I just fixed it but I figure I should finally let you all know.

**Comment by d4mation** [comment]
I just tested this on your Live Site (Without saving any changes, just in case) as well as on the Staging Server and it seems to show the Next Event properly for me.

![image](https://cloud.githubusercontent.com/assets/7770631/15191191/8eff330e-1781-11e6-82ac-5a8d2d1ea0b9.png)

Was `Type` set to `Single Event` when you noticed you had to start changing them manually? With `Type` set to `Next Event` it should grab the next upcoming Event.

**Comment by AnaHotaling** [comment]
Right... because I had to go in manually and fix the event. After this
Sunday, check. It should probably be stuck on Next Event Coming Soon!
instead of advancing to the actual next event.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
That's interesting. I'll try to look into some things in the meantime. Otherwise, I've tweaked some settings on your Staging site which may fix the problem. After Sunday we should know for certain.

**Comment by AnaHotaling** [comment]
Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
The tweaks I made on Staging worked, so I went ahead and applied those changes to your Live Site.

It should now automatically progress properly after each event!

**Comment by AnaHotaling** [comment]
Perfect! Thanks!

On Monday, May 16, 2016, Eric Defore notifications@github.com wrote:

> The tweaks I made on Staging worked, so I went ahead and applied those
> changes to your Live Site.
> 
> It should now automatically progress properly after each event!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/70#issuecomment-219412335

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
