### ISSUE TITLE
Countdown Clock Still Not Automatically Advancing

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#71]
Eva texted me that the Countdown Clock shows our next event in 366 days (or something like that)... it didn't automatically advance to the Epic Kids' Splash and Dash. I haven't manually fixed it yet so that you could take a look and see why this is happening. Thanks!

**Comment by d4mation** [comment]
It is showing the correct information for me:

![image](https://cloud.githubusercontent.com/assets/7770631/15397307/afd4b504-1dad-11e6-8d38-4bbbb9db0dc5.png)

Do you know if Eva has preformed a Hard Refresh? I don't know if this possibly could be [related to this](https://github.com/realbig/RBM_TH_EPIC/issues/26#issuecomment-170097743) back in #26 where your in-house server was holding a cache.

I'll clear our server caches again just-in-case.

**Comment by AnaHotaling** [comment]
It's fine on mine, too. At least the homepage one. I'll go check one of the
nested ones.

On Thursday, May 19, 2016, Eric Defore notifications@github.com wrote:

> It is showing the correct information for me:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/15397307/afd4b504-1dad-11e6-8d38-4bbbb9db0dc5.png
> 
> Do you know if Eva has preformed a Hard Refresh? I don't know if this
> possibly could be related to this
> https://github.com/realbig/RBM_TH_EPIC/issues/26#issuecomment-170097743
> back in #26 https://github.com/realbig/RBM_TH_EPIC/issues/26 where your
> in-house server was holding a cache.
> 
> I'll clear our server caches again just-in-case.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/71#issuecomment-220344510

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Dang it! It is the nested clock. If you go to the page called "The Epic
Team" you'll see that the countdown clock shows 366 days. I think in widget
talk, it's the page that is called primary right.

On Thursday, May 19, 2016, Eric Defore notifications@github.com wrote:

> It is showing the correct information for me:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/15397307/afd4b504-1dad-11e6-8d38-4bbbb9db0dc5.png
> 
> Do you know if Eva has preformed a Hard Refresh? I don't know if this
> possibly could be related to this
> https://github.com/realbig/RBM_TH_EPIC/issues/26#issuecomment-170097743
> back in #26 https://github.com/realbig/RBM_TH_EPIC/issues/26 where your
> in-house server was holding a cache.
> 
> I'll clear our server caches again just-in-case.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/71#issuecomment-220344510

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Ah, I was unaware of that one! It needed to be switched to use the "Next Event" settings as well.

Should be good to go now! Could you confirm that it is working on your end for me?

**Comment by AnaHotaling** [comment]
It's fixed! So will it do this automatically now, or do I have to go into
the widgets and advance it to the next event?

On Thursday, May 19, 2016, Eric Defore notifications@github.com wrote:

> Ah, I was unaware of that one! It needed to be switched to use the "Next
> Event" settings as well.
> 
> Should be good to go now! Could you confirm that it is working on your end
> for me?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/71#issuecomment-220348133

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
It should work automatically. :+1: When I tested this last weekend on your Staging site, I kept it set to "Next Event" and let it advance automatically without any interference on my part.

**Comment by AnaHotaling** [comment]
Perfect! Thanks!

On Thursday, May 19, 2016, Eric Defore notifications@github.com wrote:

> It should work automatically. 👍 When I tested this last weekend on your
> Staging site, I kept it set to "Next Event" and let it advance
> automatically without any interference on my part.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/71#issuecomment-220350791

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
