### ISSUE TITLE
Change Order of Items in Store

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#74]
I s there any way that we ca control the order in which items show up in the online store? We'd like to have the Goddess merchandise up front for now. I know people can use the pull-down menu to sort it themselves, but ... yeah, people don't notice things like that.

**Comment by d4mation** [comment]
This is actually a built-in feature of your Online Store!

If you go under WooCommerce->Settings->Products->Display, you can change the Default Sorting for your Store Page (I've done this bit for you):

![image](https://cloud.githubusercontent.com/assets/7770631/16489864/5b288152-3ea5-11e6-87c1-66480febc3c2.png)

Now if you go to Products->Sort Products you can drag and drop them into the exact order that you'd like them to appear:

![image](https://cloud.githubusercontent.com/assets/7770631/16489904/8297926e-3ea5-11e6-80e4-1e0e895aba52.png)

If you ever need to change the Default Sort ordering back to how it was before, it was originally set to "Sort by most recent".

Let me know if this works for you!

**Comment by AnaHotaling** [comment]
HOORAY! Thank you!!!!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
I've now dragged all the Goddess racing items to the top of the products list twice, and it keeps going back to the way it was, with the Waterloo Grit and Gravel stuff at the top. What do I need to do to make my changes stick? There's no Save Changes button on the page.

**Comment by d4mation** [comment]
On my end it is showing the Goddess racing items at the top with the Waterloo Grit at the end of the list. Maybe its a caching issue? I'll clear the Server Cache.

![image](https://cloud.githubusercontent.com/assets/7770631/16491390/bbd3b246-3eab-11e6-9102-4d6f6060d5e4.png)

**Comment by AnaHotaling** [comment]
Weird. When I added the two new items it showed the WGG stuff at the top.
I'll check on my phone and see!

On Thursday, June 30, 2016, Eric Defore notifications@github.com wrote:

> On my end it is showing the Goddess racing items at the top with the
> Waterloo Grit at the end of the list. Maybe its a caching issue? I'll clear
> the Server Cache.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/16491390/bbd3b246-3eab-11e6-9102-4d6f6060d5e4.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/74#issuecomment-229671639,
> or mute the thread
> https://github.com/notifications/unsubscribe/APnmPMzruhGYVfcIJnoNgxordxGXeFs-ks5qQ8_PgaJpZM4JBicp
> .

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Well... it's better, but it's not quite what I did. I did dump my cache and
relaunch my browser, too. I put all of the Goddess hoodies first, then the
Goddess tank tops, then the Goddess T shirt, then the tri kit, then the
Goddess hat, then the marathon gear, then the WGG gear. I know some won't
show up because it's out of stock, but it's still not quite in my order.
It's better, though!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
I guess I don't understand. Reading through what you wrote and looking at the site it seems that they are all in that exact order (Barring out-of-stock items, like you said).

Here's the order I'm seeing on the Live Site right now. All that seems like it could be out of place is the Medal Hanger at the end of Page 2:

Page 1
- Run Like a Goddess Ladies’ V-Neck Hooded Sweatshirt
- Tri Goddess Tri Hoodie
- Women Run the D Hoodie
- Run Like a Goddess Tank Top
- Tri Goddess Tri Kit
- Swim Bike Done Aquabike T-Shirt
- Run Like a Goddess Trucker Hat
- Ann Arbor Marathon Trucker Hat
- Ann Arbor Marathon Running Hat
- Ann Arbor Marathon Women’s T-Shirt
- Ann Arbor Marathon Women’s Tech T-Shirt
- Ann Arbor Marathon Tech T-Shirt

Page 2
- Ann Arbor Marathon 1/4-Zip Jacket
- Ann Arbor Marathon Jacket
- Ann Arbor Marathon Beanie
- Waterloo Grit and Gravel T-Shirt
- Waterloo Grit and Gravel Women’s Cycling Jersey
- Waterloo Grit and Gravel Hoodie
- Ann Arbor Marathon Medal Hanger

Is it showing a different order for you?

**Comment by AnaHotaling** [comment]
Yes! How bizarre! This is what I see:

Run Like a Goddess tank top
Run Like a Goddess Hooded Sweatshirt
Women Run the D Hooded Sweatshirt
Tri Goddess Tri Kit
Ann Arbor Marathon Tech Shirt
Tri Goddess Tri Hoodie
Swim Bike Done Aquabike T-Shirt
Waterloo Grit and Gravel Women's Cycling Jersey
Waterloo Grit and Gravel Hooded Sweatshirt
Waterloo Grit ad Gravel T-Shirt
Ann Arbor Marathon Beanie

That's just page one, but so not like yours! And I did dump my cache, and I
even powercycled the stupid Cradlepoint router and re-tethered the MiFi
doodad for our Internet, then launched Firefox again. Well, once I was back
on Wifi, that is. Oh well. If you see it the way I want it to be seen, that
matters more than what I'm seeing, right?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
That's quite strange. I cleared the server caches before posting that comment, so anything that could be preventing it from showing right for you on our end should be taken care of.

I'm really thinking it must be a caching issue of _some kind_, but you power cycled and cleared out just about everything possible... Aside from server or local caches I cannot think of anything else that could cause something like this.

I suppose since I'm seeing it correctly, we'll give it a little more time to see if it decides to show properly for you since I figure if I'm seeing it correctly, so should visitors to your site.

**Comment by AnaHotaling** [comment]
That's what matters! Thanks, Eric!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
