### ISSUE TITLE
Make Hotel Field in Template a WYSIWYG Field

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#75]
We've been getting email after email from people who want to click the links for hotel registration, only to learn they have to copy and paste the link into their browser. Can we please make this field a WYSIWYG field so that I can link the hotel URLS and participants don't complain? :)

**Comment by brashrebel** [comment]
Can you give me an example? [This one](http://epicraces.com/event/battle-of-waterloo/) works correctly.

**Comment by AnaHotaling** [comment]
Well, here, I suppose, as this was the one in question:

http://epicraces.com/event/detroit-goddess/

It's my understanding that the Marriott reps want to actually see their
link, and that putting it under More Information doesn't show the actual
link.

Plus apparently participants don't understand that they can click More
Information...

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
Ok, thanks for clarifying. I would definitely not put their full link in the description as it will definitely confuse people. If you have reason to believe that users are legitimately confused about how to get to the hotel site then we can simply change the "More information" text to be more descriptive. Suggest something that you think is more clear in every use case.

And I'd also request clarification on what the hotel wants. You're saying they have some kind of requirement that users visually see the address? That would certainly be odd and it strikes me that you shouldn't have to oblige if you don't care to. It is your site.

**Comment by AnaHotaling** [comment]
Yes! There was even a post on Facebook today about how the link wasn't
working, and two of us (Mary, the RD for Detroit Goddess) and I had to
address it. People just expect a link to click through, even if it's
obviously just text.

I like the idea of changing the More Information to something like Click
Here to Reserve Your Room or something of that nature.

And yes, the Detroit Marriott people are very... interested in making sure
their link is up. They must have written about five times last year and I'd
like to curtail that this year! Let's try changing the More Information.
Perhaps the Click Here to Reserve Your Room will be enough. If not, then
I'll let you know. We have to keep our host hotel happy, too, even if it
seems a little... well, you can think of a word.

THANKS!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
I'll add this to our to-do list. It will be about two weeks until we can get to it.

**Comment by AnaHotaling** [comment]
That's fine! Although if you can do it sooner, that'd be fine, too. Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
