### ISSUE TITLE
Instructions on how to refund someone for an item purchased on our site

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#76]
So... Donna Silverberg cancelled her order for $175. It says Processing under Status. Under View, there is the choice of Refunded, but I'm not sure selecting that is all I need to do to refund her the money. What needs to be done? Do I have to do this through Paypal?

**Comment by brashrebel** [comment]
@AnaHotaling please follow [these instructions](https://docs.woothemes.com/document/woocommerce-refunds/) to setup and then process refunds.
