### ISSUE TITLE
http://www.womenrunthed.com coming up as a 404 error

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#77]
Not sure what is going on here. The link:

http://www.womenrunthed.com yields a 404

but

http://womenrunthed.com is fine.

And of course, we use the www version in all of our ads and publicity materials.

Is this something that you can fix, or is it something that has to be done via Go Daddy? Checked with my network guy aka husband and he started to explain to me that you guys can fix this when he got a work-related call, so.... help?

**Comment by brashrebel** [comment]
I just made a change. Can you test this again in one hour?

**Comment by AnaHotaling** [comment]
Sure! Thanks, Kyle!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
All set! Thanks!!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
