### ISSUE TITLE
Shipping with local pick-up vs flat-rate 

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#78]
I know that we requested about a year ago that flat-rate shipping for $10 be the default, since Eva didn't want to have people coming to the office to pick up merchandise and didn't want the hassle of remembering to bring specific items to our events for pick up.

But now we have a pre-sale of Battle of Waterloo merchandise. For each item, I went in and selected shipping as "local pick-up." Then, for each variation, I selected "same as parent" (except for the hats, which have no variation." 

People were still being charged $10, so we have a bunch of refunds to do now. 

I went in again today and changed all the "same as parent" to "local pick-up" to make it redundant. Will that fix this issue?

**Comment by brashrebel** [comment]
Yeah, that sounds right to me.

**Comment by AnaHotaling** [comment]
Now we need someone to buy something to see if it's fixed. Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by BigActual** [comment]
Closing. Store is off-site
