### ISSUE TITLE
Newsletter sign-ups

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#81]
On the homepage, we have an option where people can add their email address to our database to receive our mailings. Currently this is set so that new emails are added to our mailing list on iContact. We are no longer going to be using iContact for email blasts; we will be sending our emails out through Run Sign Up. We would like all new email addresses to be added to our main email list there, but we're not sure if this can be done automatically or if it must be done manually. I haven't yet contacted Jordan at RSU yet for his input... what are your thoughts on this?

**Comment by brashrebel** [comment]
Depends on RSU. Never used that service before. If they have some kind of system like iContact did then we can make the switch fairly easily. Otherwise...well let's just see what they offer. When you get information from them like "Here's what other customers do" share it with us please.

**Comment by AnaHotaling** [comment]
So far, no real word... they offer it for club and teams, but not for race companies that need to keep track of email-list subscribers. I was told that they'd look into this more. In the meantime, is it possible to deactivate the link to iContact and collect any newly added emails into a CSV or some sort of file? We just got an email from a woman who accidentally unsubscribed herself and I have no idea what to do with her email address!

**Comment by AnaHotaling** [comment]
Okay, so here is the final word from Run Sign Up:

You will have to keep bringing them over for now.  The only run around option would be for you to create a club, then use the club widget for newsletter sign up.  At that point you are still having to port them over.  But it would remove the need for icontact.  It's sloppy until we get the widget added in at the partner level. 

So... bleh. We definitely need to disconnect the "Sign Up for Our Newsletter" field from iContact. Perhaps the best way to deal with this for now is for any new sign ups to just be imported into a CSV file, and then we get a weekly CSV file from you that we import into Run Sign Up. Is that possible?

**Comment by brashrebel** [comment]
Yeah, I think we could do that. So you're not going to use iContact anymore?

**Comment by AnaHotaling** [comment]
Great timing!

Eva and I were talking, and we think it's probably easier for me to just
continue to export the email addresses from iContact into RSU on a weekly
or monthly basis than having to set up some sort of CSV of the week system.
We still have it, because it's great for layout. But they were getting
silly with their pricing. Thanks!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
So is there anything needed anymore?

**Comment by AnaHotaling** [comment]
Nope, not at this time. Until it starts bugging us again! Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
