### ISSUE TITLE
Spacing needed between Divisions and Awards

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#82]
Hello there! If you go to our American Home Fitness Detroit Goddess page and click the button for Lodging, it'll jump you down to the block that has Awards, Divisions, Lodging, etc. Divisions runs right into Awards. Can more spacing be put in to separate these two sections?

**Comment by brashrebel** [comment]
We can add this to our to-do list for next week.

**Comment by AnaHotaling** [comment]
Thanks!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
![image](https://cloud.githubusercontent.com/assets/7770631/18550017/efdc86e8-7b1f-11e6-9925-fd0a79a1c36d.png)

**Comment by AnaHotaling** [comment]
Thank you!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
