### ISSUE TITLE
Repetitive Contact Us Submissions

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#83]
For the past couple of weeks, when someone uses the Contact Us submission form, Eva and I receive anywhere between 6 to 12 copies of that form, all one right after the other in a matter of seconds. We thought maybe it might be someone pressing the Submit button repeatedly, but it's happened far too many times. Can you check this, please? Thanks!

**Comment by brashrebel** [comment]
We'll take a look.

**Comment by AnaHotaling** [comment]
What ended up happening? Just curious!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Changes are being uploaded as I type.

Basically, I converted your Contact Form to work with Gravity Forms (Which you were already using for your "Heart Hero Nomination" Form). The one you were using before was built into the Parent Theme itself and wasn't very maintainable.

Now it can be easily changed whenever necessary (With a nice user-interface to boot!) and still retains all of the old functionality. Gravity Forms is a very respected solution for building Email Forms in WordPress, so any strange multiple email issues should no longer occur 👍 

I did what I could to make the form look identical to the old one. The only real difference is that now the E-Mail and Message Fields are required to help ensure no weird blank emails get through.
![image](https://cloud.githubusercontent.com/assets/7770631/18587810/bed087c0-7bf1-11e6-9216-c1ecab4c8d29.png)

**Comment by AnaHotaling** [comment]
That works! It was just weird. Suddenly we got 6 emails from one person. We
thought she was just impatient. Then it happened with another person, who
apologized for clicking Submit too often. So we thought maybe it was a
fluke. But then it happened again and again, so I told Eva I'd start a
Github.

Although I can definitely see impatient people just clicking submit over
and over!

The overzealous clicker noted that she didn't receive any kind of online
confirmation that her contact form went through. Do we have something set
up that says something like "Thank you for contacting us! An Epic Races
staff member will be in touch with you shortly." Or anything? That might
keep the clickers at bay!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Indeed you do! In fact, it is set to replace the form entirely by this message so they won't be able to repeatedly submit the form.

**Comment by AnaHotaling** [comment]
Well, good! I guess the clicker just didn't pay attention. Thanks, Eric!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
I'm back! We received a submission through the updated Contact Us form...
and both Eva and I found it confusing. The email itself looks like it is
coming from eva@epicraces.com instead of coming from the person who
submitted the form. Can that be changed back to being from the sender
instead of from Eva?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Yep, that can be changed. I set it to being from Eva rather than the sender
to hopefully keep submissions out of a spam box. I will reset it to   be
from the sender.

**Comment by AnaHotaling** [comment]
Thank you!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Should be all set!

**Comment by AnaHotaling** [comment]
Thanks again!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
