### ISSUE TITLE
Staff Page Order

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#87]
Help! I have been trying to get the staff page entries in the order Eva asked me to put them in... but Ryan and Zach keep showing up in the middle of the Event Staff tier, even though I keep dragging their names to the bottom of the list. They should be the last two staffers on the list, under Lou Ann Dixon. How can I get them to stay in place?

**Comment by d4mation** [comment]
I believe I've managed to address this. You may need to quickly rearrange the rest of the Staff, but Zach and Ryan are at the bottom correctly now 👍

**Comment by AnaHotaling** [comment]
We are good! THANKS!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
