### ISSUE TITLE
Change Pricing Field

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#90]
Eva would like our event page template's pricing field changed so that previous pricing is no longer visible. For example, on January 1, the Dec. 1-31 registration pricing should disappear so that people cannot see what the previous pricing was, only current. I'll ask about future pricing, but wanted to get this started!

**Comment by AnaHotaling** [comment]
Yes, correct and future, not past. So pretty much expiring the listing once the final date is met.

**Comment by brashrebel** [comment]
Cool idea. We could do this. This would be two billable hours.

**Comment by d4mation** [comment]
Do you mean this Pricing Field?

![image](https://cloud.githubusercontent.com/assets/7770631/21393272/ba2beaa0-c761-11e6-851a-f5ceed01075f.png)

That's currently controlled by a WYSIWYG editor. 

![image](https://cloud.githubusercontent.com/assets/7770631/21393378/187c1468-c762-11e6-9426-2874528d74e1.png)

Changing that to be something else so that we could remove those rows once a date has passed wouldn't be a huge deal on our end, but that would mean that every single Event would need to have that field updated for the new system. It could become a lengthy process once we've got something working in order to make sure it is working properly on each Event (Because if one were to be missed, it could lead to undesirable results).

The best way I can think of handling it would be creating a second, new field and show that one if there's any data. That way the old version of the Pricing Table will show if that's the only one filled out. Then Events could get updated to use the new Pricing Field at your leisure and eventually we could just delete the old Pricing Field once we know all the Events have been updated.

**Comment by AnaHotaling** [comment]
But creating a second new field would also mean having to update every
single event page anyway. :) And if the old field is still up, showing
earlier pricing, that defeats the purpose. Eva doesn't want anyone to see
earlier pricing. She wants earlier pricing gone once that pricing expires.

So... what to do?

**Comment by d4mation** [comment]
I don't think I was clear. The Old Field would exist within the "Edit Event" interface, but if the New Field were filled out for an Event, the Old Field would not show for Visitors.

This way you guys could convert to using the New Field over time without needing to rush through each Event all at once.

**Comment by AnaHotaling** [comment]
Okay... so how would the new field work? Same as the old, but with
automatic deletions of expired pricing?

**Comment by d4mation** [comment]
Honestly, I haven't fully decided yet. But I intend to make it easy to manage on your end. It should be much simpler than creating a table by hand in a WYSIWYG for sure.

**Comment by AnaHotaling** [comment]
Well, that's got my vote then!!!

**Comment by d4mation** [comment]
Alright, I've got something working for you. Here's an example of it in action:

![image](https://cloud.githubusercontent.com/assets/7770631/21402540/f66af176-c786-11e6-9bc0-dc8bb292e10a.png)

It looks pretty much the same as it did before, but here I've made an example in my local environment as to what it would look like if all the other Deadlines had already passed. It removed them from the table and only shows the last one, which is for Race Day.

For the Edit Event Screen, things look a bit intimidating at first, but it will end up being faster once you get the hang of it. Here is what a single Row looks like:

![image](https://cloud.githubusercontent.com/assets/7770631/21402620/61fada50-c787-11e6-97ba-4c59ea4e2bd8.png)

You add in each Race-Type individually and assign it a Title and a Price Point. From there you can assign a Start Date and and End Date for that Price Point, as well as any additional notes (Such as "Cash Only Until Sold Out" or things like that.

This way the Deadline is associated with each Price for each Race Type, but you can have as many or as Few Race Types as you'd like. So if there's only one Price Point per Deadline, that's fine. If you have 7 Price Points per Deadline that is also fine. It automatically structures the Table for you. Each "Race Type" that you add effectively becomes a column in the Table.

For each additional Row, you do not need to actually enter the Race Title. However, as you get further down the Page that may help you remember that the first Price is for the 5K and so on.

If the End Date has already passed for a Row (And it isn't the last Row), it will be automatically removed on the Front End of the Website. It will still show on the Edit Screen, but Visitors will not see it. This way if you want to adjust dates and have it show again you are able to.

If the New Pricing Field is not filled out, it will fallback to the Old one.

This code is now Live on your site!

**Comment by AnaHotaling** [comment]
Excellent! Thanks! Will give it a whirl once I get through all the email
today. If I've got any questions, I'll let you know. Thanks again!



Ana Hotaling
*Director of Inbound Marketing/Asst. Race Director, Epic Races*

│ m. 734.585.7101
│ a. 600 S. Wagner Road, Ann Arbor, MI 48103
│ w. www.epicraces.com
│ e. ana@epicraces.com

<https://www.facebook.com/epicracesevents>. <https://twitter.com/epicraces>.
<https://www.instagram.com/epicraces/>.



<https://newoldstamp.com/editor/>

**Comment by AnaHotaling** [comment]
Reopening this. Noticed on the Suburban Chevrolet Ann Arbor Goddess event page that the earlier pricing is not expiring. All previous pricing is still visible. I haven't checked any other event pages; hoping this is an isolated incident. Can you please fix this so that all earlier pricing expires when a new price increase takes effect? It's the whole reason we switched to this new pricing field. Thanks!
