### ISSUE TITLE
New Epic Page?

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#91]
Wish I'd submitted this before your call with Eva. Eva would like us to have a page like this: http://americamultisport.com/v6/why-race-with-ams/. 

Looks very graphic heavy and probably not possible with our theme?

**Comment by brashrebel** [comment]
If you want to make an infographic like that and just insert it into the page, you're entirely welcome to do so. There's nothing that prevents using an infographic.

**Comment by AnaHotaling** [comment]
I was thinking it was more of a Photoshop thing. Not sure how individual
links would work, though.

**Comment by brashrebel** [comment]
On the page you linked to, it is just one giant image. We call those infographics. You can make one if you like. There's online tools to help make them or just use Photoshop. Making links inside them is not easy though. Also, it's generally not a great experience for users as text in images is always a bad idea. If you put text in an image, people can't translate it, people with disabilities can't access it on alternative devices, it doesn't scale well for smaller screens, people can't copy and paste it, they can't use their browser zoom to increase the font size, etc. Text in images is bad....usually.

**Comment by AnaHotaling** [comment]
So a page like that is pretty much a bad idea, all things considered.

**Comment by brashrebel** [comment]
There are instances in which it can be useful. Those kinds of long, vertical images are great for sharing visual things on Pinterest. But not for important information.

**Comment by AnaHotaling** [comment]
Okay! I'll break the news gently. Thanks!
