### ISSUE TITLE
Events out of order again

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#92]
I haven't looked into this myself but the client has reported to me that they are once again not appearing in the correct order. Asking for specifics but it appears to be a recurring problem. Ana is sick so I'm getting this message from Eva.

**Comment by d4mation** [comment]
If this is in reference to the List here:

![image](https://cloud.githubusercontent.com/assets/7770631/21199770/e5866b16-c212-11e6-8af4-614570ba4c15.png)

It is due to the top two Events being set to Sticky, as was the issue over in #88.

**Comment by d4mation** [comment]
In #88 we discovered it caused a lot of other issues with ordering such as in the Menu as well, so it could be causing problems everywhere.

It seems like Events should never be given "Sticky", but a few have been at some point or another and are slowly surfacing.
