### ISSUE TITLE
Can't remove old link

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#94]
On the Frosty Ski Fest page, an old link to an outdated NordicSkiRacer.com page shows up on the publicly viewed page beneath Venue. On the page I edit, the field for Web Site is empty. Not sure where to find this link so I can delete it.

**Comment by brashrebel** [comment]
All venues are managed here: http://epicraces.com/wp-admin/edit.php?post_type=tribe_venue

That way you can easily reuse venues on other events.

**Comment by AnaHotaling** [comment]
The link is tied into the venue??

**Comment by brashrebel** [comment]
Yep. The venue can have its own website defined. If you change it there, it will change it on every event that uses that venue.

**Comment by AnaHotaling** [comment]
Got it. Thanks!!!!!
