### ISSUE TITLE
Favicon issues

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#96]
Eva is pulling up what looks like a Marriott favicon when she opens Epic in Chrome. I get no favicon at all in Firefox, Chrome, or Safari. Haven't checked Exploder. Do you have a favicon for us?

**Comment by brashrebel** [comment]
No, we don't. But if you login and go to Customize - > Site Identity - > Site Icon you can select an image.

**Comment by AnaHotaling** [comment]
I'm logged in but I can't find where Customize is. Link please, or path to
it ... thanks!

**Comment by brashrebel** [comment]
@d4mation can you make sure please that Ana's role allows access to the customizer?

**Comment by d4mation** [comment]
@AnaHotaling You can find "Customize" under Appearance -> Customize. I just checked and you do have access to it.

From there, follow @brashrebel's instructions and you'll find a place to add a Favicon 👍

**Comment by AnaHotaling** [comment]
Quick q: this doesn't automatically generate a favicon?

**Comment by d4mation** [comment]
It will generate a Favicon based on the uploaded image, but I actually just realized that while you have access to the "Site Identity" menu, the Site Icon field doesn't show for you. I'll fix that really quick, my bad.

**Comment by AnaHotaling** [comment]
Oh good. I've created favicons in the past, but it's such a hassle to do
them manually! Thanks!

**Comment by d4mation** [comment]
Just made it so that you definitely have access to the Site Icon field. If you follow the directions outlined above it should set it for you :+1:
