### ISSUE TITLE
Sky Tri listing

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#97]
Sky Tri is not coming up in chronological order on the Events menu. It doesn't have the sticky calendar thing checked. Not sure what to do to get it back in order!

**Comment by AnaHotaling** [comment]
Amend that... everything in the Run category is in the right chronological order, but the Goddess, Triathlon, Duathlon, and Aquabike categories are all messed up. No sticky calendars involved.

**Comment by d4mation** [comment]
This fix is live on your site!

**Comment by AnaHotaling** [comment]
Woohoo!! Thanks!!!
