### ISSUE TITLE
Sign Up for Newsletter Not Working

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#98]
Eva informs me that the field on our homepage where people can sign up for our mailing list is not functioning. Can this be checked and modified so that it saves all new email addresses in a CSV file we can access to upload to Run Sign Up?

**Comment by brashrebel** [comment]
Looks like the error message comes from iContact. The code for that newsletter signup was just copied and pasted from iContact so it will be necessary to reach out to them about this. Can you try it yourself and then reach out to iContact to ask them why an error is being returned?

**Comment by AnaHotaling** [comment]
We no longer use iContact for email blasts, only for designing our blasts.
We've removed all of our mailing lists from there in order to lower the
monthly fee to the bare minimum. We mail everything from Run Sign Up. There
is no way to link to Run Sign Up to add email addresses there directly (I
asked). What we need is a way to store the newly submitted emails in some
sort of file, preferably a CSV, which one of us can check each week and
upload to our mailing list on Run Sign Up until such a time that they get
around to developing this functionality. Can this be done?

**Comment by brashrebel** [comment]
Yeah, this can be done in an hour and a half of our time by the end of next week.

**Comment by AnaHotaling** [comment]
Got it! The other question then would be what I'd need to create on
Icontact to receive newly submitted email addresses. Guessing I should
check with them, huh?

**Comment by brashrebel** [comment]
Now I'm confused. I thought you weren't putting new subscribers there? Are you saying you want the new subscribers to go to _both_ iContact and a CSV file?

**Comment by AnaHotaling** [comment]
We wanted to avoid having any lists on icontact because we are at the
lowest subscriber level, but as long as I go in and pull the names off of
iContact and bring them to RSU it should hopefully not cause us problems.
This would also forego our needing a recipient CSV file on the Epic
back-end.

My question is do I just go and create "Epic Mailing List" on icontact or
are there parameters I need to follow to interface it with our site?

**Comment by brashrebel** [comment]
I don't know much about how iContact works. If they give you a unique embed code for each list then we can just update what's there on the site. So I guess you guys just need to decide if you want to simply get the subscribers from the site or from iContact.

**Comment by AnaHotaling** [comment]
Okay, that's what I was asking: what we need from icontact. Guess I'm
looking for an embed code. I'll be back!

**Comment by AnaHotaling** [comment]
Okay... I think this is it:

<script type="text/javascript" src="//
app.icontact.com/icp/core/mycontacts/signup/designer/form/automatic?id=74&cid=606452&lid=1449
"></script>



Ana Hotaling
*Director of Inbound Marketing/Asst. Race Director, Epic Races*

│ m. 734.585.7101
│ a. 600 S. Wagner Road, Ann Arbor, MI 48103
│ w. www.epicraces.com
│ e. ana@epicraces.com

<https://www.facebook.com/epicracesevents>. <https://twitter.com/epicraces>.
<https://www.instagram.com/epicraces/>.



<https://newoldstamp.com/editor/>

**Comment by d4mation** [comment]
@AnaHotaling It looks like what you were given was an embed code for the iContact Form, which I don't think is what you want.

From what I understand, you are only using iContact to create/design the email itself, but are using Run Sign Up to actually send them out, correct?

If the form from that embed code were to be filled out, it would just add the email address to the iContact List. It seems like that isn't what you want as you're trying to stay in a lower pricing tier.

I think what may work best for you in this case would be to create a custom Form on your website that just gathers email addresses. Then every week on a schedule it would email you an export of all the entries as a CSV so that you can ensure the mailing list is up-to-date when you send it out via Run Sign Up.

Is this the type of functionality you'd be looking for?

**Comment by AnaHotaling** [comment]
What Eva wants is for people to be able to sign up on the Epic site for the
mailing list, and gave that new email address added to the list on
iContact. Every couple of weeks, I will pull the CSV and add those new
emails to our mailing list on Run Sign Up.

I personally would prefer to have the CSV generated on the Epic site but,
since we are already paying for iContact (we can go up to 500), it doesn't
make sense to pay for an additional CSV on Epic's site. Now, if this could
be done without an additional charge... then absolutely!

**Comment by brashrebel** [comment]
If we're adding a feature there will be a charge. Sorry.

**Comment by AnaHotaling** [comment]
I know! Just letting you know why we'll stick with iContact for now. When
we finally redesign the site, we can hopefully add this!

**Comment by d4mation** [comment]
Just replaced your old iContact form with the new embed code and styled it to match the old one :+1:

Changes are live on your site!
